// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.4
// source: injective_rfq_rpc.proto

package injective_rfq_rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InjectiveRfqRPCClient is the client API for InjectiveRfqRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InjectiveRfqRPCClient interface {
	// Create RFQ request
	Request(ctx context.Context, in *RequestRequest, opts ...grpc.CallOption) (*RequestResponse, error)
	// Stream RFQ requests
	StreamRequest(ctx context.Context, in *StreamRequestRequest, opts ...grpc.CallOption) (InjectiveRfqRPC_StreamRequestClient, error)
	// Create RFQ quote
	Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error)
	// Stream RFQ quotes
	StreamQuote(ctx context.Context, in *StreamQuoteRequest, opts ...grpc.CallOption) (InjectiveRfqRPC_StreamQuoteClient, error)
	// List RFQ settlements
	ListSettlement(ctx context.Context, in *ListSettlementRequest, opts ...grpc.CallOption) (*ListSettlementResponse, error)
	// Stream RFQ settlements
	StreamSettlement(ctx context.Context, in *StreamSettlementRequest, opts ...grpc.CallOption) (InjectiveRfqRPC_StreamSettlementClient, error)
	// Create a conditional TP/SL order
	CreateConditionalOrder(ctx context.Context, in *CreateConditionalOrderRequest, opts ...grpc.CallOption) (*CreateConditionalOrderResponse, error)
	// List conditional TP/SL orders
	ListConditionalOrders(ctx context.Context, in *ListConditionalOrdersRequest, opts ...grpc.CallOption) (*ListConditionalOrdersResponse, error)
	// Bidirectional stream for takers: send requests, receive quotes
	TakerStream(ctx context.Context, opts ...grpc.CallOption) (InjectiveRfqRPC_TakerStreamClient, error)
	// Bidirectional stream for makers: receive requests, send quotes
	MakerStream(ctx context.Context, opts ...grpc.CallOption) (InjectiveRfqRPC_MakerStreamClient, error)
}

type injectiveRfqRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewInjectiveRfqRPCClient(cc grpc.ClientConnInterface) InjectiveRfqRPCClient {
	return &injectiveRfqRPCClient{cc}
}

func (c *injectiveRfqRPCClient) Request(ctx context.Context, in *RequestRequest, opts ...grpc.CallOption) (*RequestResponse, error) {
	out := new(RequestResponse)
	err := c.cc.Invoke(ctx, "/injective_rfq_rpc.InjectiveRfqRPC/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *injectiveRfqRPCClient) StreamRequest(ctx context.Context, in *StreamRequestRequest, opts ...grpc.CallOption) (InjectiveRfqRPC_StreamRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &InjectiveRfqRPC_ServiceDesc.Streams[0], "/injective_rfq_rpc.InjectiveRfqRPC/StreamRequest", opts...)
	if err != nil {
		return nil, err
	}
	x := &injectiveRfqRPCStreamRequestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InjectiveRfqRPC_StreamRequestClient interface {
	Recv() (*StreamRequestResponse, error)
	grpc.ClientStream
}

type injectiveRfqRPCStreamRequestClient struct {
	grpc.ClientStream
}

func (x *injectiveRfqRPCStreamRequestClient) Recv() (*StreamRequestResponse, error) {
	m := new(StreamRequestResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *injectiveRfqRPCClient) Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error) {
	out := new(QuoteResponse)
	err := c.cc.Invoke(ctx, "/injective_rfq_rpc.InjectiveRfqRPC/Quote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *injectiveRfqRPCClient) StreamQuote(ctx context.Context, in *StreamQuoteRequest, opts ...grpc.CallOption) (InjectiveRfqRPC_StreamQuoteClient, error) {
	stream, err := c.cc.NewStream(ctx, &InjectiveRfqRPC_ServiceDesc.Streams[1], "/injective_rfq_rpc.InjectiveRfqRPC/StreamQuote", opts...)
	if err != nil {
		return nil, err
	}
	x := &injectiveRfqRPCStreamQuoteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InjectiveRfqRPC_StreamQuoteClient interface {
	Recv() (*StreamQuoteResponse, error)
	grpc.ClientStream
}

type injectiveRfqRPCStreamQuoteClient struct {
	grpc.ClientStream
}

func (x *injectiveRfqRPCStreamQuoteClient) Recv() (*StreamQuoteResponse, error) {
	m := new(StreamQuoteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *injectiveRfqRPCClient) ListSettlement(ctx context.Context, in *ListSettlementRequest, opts ...grpc.CallOption) (*ListSettlementResponse, error) {
	out := new(ListSettlementResponse)
	err := c.cc.Invoke(ctx, "/injective_rfq_rpc.InjectiveRfqRPC/ListSettlement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *injectiveRfqRPCClient) StreamSettlement(ctx context.Context, in *StreamSettlementRequest, opts ...grpc.CallOption) (InjectiveRfqRPC_StreamSettlementClient, error) {
	stream, err := c.cc.NewStream(ctx, &InjectiveRfqRPC_ServiceDesc.Streams[2], "/injective_rfq_rpc.InjectiveRfqRPC/StreamSettlement", opts...)
	if err != nil {
		return nil, err
	}
	x := &injectiveRfqRPCStreamSettlementClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InjectiveRfqRPC_StreamSettlementClient interface {
	Recv() (*StreamSettlementResponse, error)
	grpc.ClientStream
}

type injectiveRfqRPCStreamSettlementClient struct {
	grpc.ClientStream
}

func (x *injectiveRfqRPCStreamSettlementClient) Recv() (*StreamSettlementResponse, error) {
	m := new(StreamSettlementResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *injectiveRfqRPCClient) CreateConditionalOrder(ctx context.Context, in *CreateConditionalOrderRequest, opts ...grpc.CallOption) (*CreateConditionalOrderResponse, error) {
	out := new(CreateConditionalOrderResponse)
	err := c.cc.Invoke(ctx, "/injective_rfq_rpc.InjectiveRfqRPC/CreateConditionalOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *injectiveRfqRPCClient) ListConditionalOrders(ctx context.Context, in *ListConditionalOrdersRequest, opts ...grpc.CallOption) (*ListConditionalOrdersResponse, error) {
	out := new(ListConditionalOrdersResponse)
	err := c.cc.Invoke(ctx, "/injective_rfq_rpc.InjectiveRfqRPC/ListConditionalOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *injectiveRfqRPCClient) TakerStream(ctx context.Context, opts ...grpc.CallOption) (InjectiveRfqRPC_TakerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &InjectiveRfqRPC_ServiceDesc.Streams[3], "/injective_rfq_rpc.InjectiveRfqRPC/TakerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &injectiveRfqRPCTakerStreamClient{stream}
	return x, nil
}

type InjectiveRfqRPC_TakerStreamClient interface {
	Send(*TakerStreamStreamingRequest) error
	Recv() (*TakerStreamResponse, error)
	grpc.ClientStream
}

type injectiveRfqRPCTakerStreamClient struct {
	grpc.ClientStream
}

func (x *injectiveRfqRPCTakerStreamClient) Send(m *TakerStreamStreamingRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *injectiveRfqRPCTakerStreamClient) Recv() (*TakerStreamResponse, error) {
	m := new(TakerStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *injectiveRfqRPCClient) MakerStream(ctx context.Context, opts ...grpc.CallOption) (InjectiveRfqRPC_MakerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &InjectiveRfqRPC_ServiceDesc.Streams[4], "/injective_rfq_rpc.InjectiveRfqRPC/MakerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &injectiveRfqRPCMakerStreamClient{stream}
	return x, nil
}

type InjectiveRfqRPC_MakerStreamClient interface {
	Send(*MakerStreamStreamingRequest) error
	Recv() (*MakerStreamResponse, error)
	grpc.ClientStream
}

type injectiveRfqRPCMakerStreamClient struct {
	grpc.ClientStream
}

func (x *injectiveRfqRPCMakerStreamClient) Send(m *MakerStreamStreamingRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *injectiveRfqRPCMakerStreamClient) Recv() (*MakerStreamResponse, error) {
	m := new(MakerStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// InjectiveRfqRPCServer is the server API for InjectiveRfqRPC service.
// All implementations must embed UnimplementedInjectiveRfqRPCServer
// for forward compatibility
type InjectiveRfqRPCServer interface {
	// Create RFQ request
	Request(context.Context, *RequestRequest) (*RequestResponse, error)
	// Stream RFQ requests
	StreamRequest(*StreamRequestRequest, InjectiveRfqRPC_StreamRequestServer) error
	// Create RFQ quote
	Quote(context.Context, *QuoteRequest) (*QuoteResponse, error)
	// Stream RFQ quotes
	StreamQuote(*StreamQuoteRequest, InjectiveRfqRPC_StreamQuoteServer) error
	// List RFQ settlements
	ListSettlement(context.Context, *ListSettlementRequest) (*ListSettlementResponse, error)
	// Stream RFQ settlements
	StreamSettlement(*StreamSettlementRequest, InjectiveRfqRPC_StreamSettlementServer) error
	// Create a conditional TP/SL order
	CreateConditionalOrder(context.Context, *CreateConditionalOrderRequest) (*CreateConditionalOrderResponse, error)
	// List conditional TP/SL orders
	ListConditionalOrders(context.Context, *ListConditionalOrdersRequest) (*ListConditionalOrdersResponse, error)
	// Bidirectional stream for takers: send requests, receive quotes
	TakerStream(InjectiveRfqRPC_TakerStreamServer) error
	// Bidirectional stream for makers: receive requests, send quotes
	MakerStream(InjectiveRfqRPC_MakerStreamServer) error
	mustEmbedUnimplementedInjectiveRfqRPCServer()
}

// UnimplementedInjectiveRfqRPCServer must be embedded to have forward compatible implementations.
type UnimplementedInjectiveRfqRPCServer struct {
}

func (UnimplementedInjectiveRfqRPCServer) Request(context.Context, *RequestRequest) (*RequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) StreamRequest(*StreamRequestRequest, InjectiveRfqRPC_StreamRequestServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamRequest not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) Quote(context.Context, *QuoteRequest) (*QuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Quote not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) StreamQuote(*StreamQuoteRequest, InjectiveRfqRPC_StreamQuoteServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamQuote not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) ListSettlement(context.Context, *ListSettlementRequest) (*ListSettlementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSettlement not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) StreamSettlement(*StreamSettlementRequest, InjectiveRfqRPC_StreamSettlementServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamSettlement not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) CreateConditionalOrder(context.Context, *CreateConditionalOrderRequest) (*CreateConditionalOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConditionalOrder not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) ListConditionalOrders(context.Context, *ListConditionalOrdersRequest) (*ListConditionalOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConditionalOrders not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) TakerStream(InjectiveRfqRPC_TakerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method TakerStream not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) MakerStream(InjectiveRfqRPC_MakerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method MakerStream not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) mustEmbedUnimplementedInjectiveRfqRPCServer() {}

// UnsafeInjectiveRfqRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InjectiveRfqRPCServer will
// result in compilation errors.
type UnsafeInjectiveRfqRPCServer interface {
	mustEmbedUnimplementedInjectiveRfqRPCServer()
}

func RegisterInjectiveRfqRPCServer(s grpc.ServiceRegistrar, srv InjectiveRfqRPCServer) {
	s.RegisterService(&InjectiveRfqRPC_ServiceDesc, srv)
}

func _InjectiveRfqRPC_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InjectiveRfqRPCServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/injective_rfq_rpc.InjectiveRfqRPC/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InjectiveRfqRPCServer).Request(ctx, req.(*RequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InjectiveRfqRPC_StreamRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequestRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InjectiveRfqRPCServer).StreamRequest(m, &injectiveRfqRPCStreamRequestServer{stream})
}

type InjectiveRfqRPC_StreamRequestServer interface {
	Send(*StreamRequestResponse) error
	grpc.ServerStream
}

type injectiveRfqRPCStreamRequestServer struct {
	grpc.ServerStream
}

func (x *injectiveRfqRPCStreamRequestServer) Send(m *StreamRequestResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _InjectiveRfqRPC_Quote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InjectiveRfqRPCServer).Quote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/injective_rfq_rpc.InjectiveRfqRPC/Quote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InjectiveRfqRPCServer).Quote(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InjectiveRfqRPC_StreamQuote_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamQuoteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InjectiveRfqRPCServer).StreamQuote(m, &injectiveRfqRPCStreamQuoteServer{stream})
}

type InjectiveRfqRPC_StreamQuoteServer interface {
	Send(*StreamQuoteResponse) error
	grpc.ServerStream
}

type injectiveRfqRPCStreamQuoteServer struct {
	grpc.ServerStream
}

func (x *injectiveRfqRPCStreamQuoteServer) Send(m *StreamQuoteResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _InjectiveRfqRPC_ListSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InjectiveRfqRPCServer).ListSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/injective_rfq_rpc.InjectiveRfqRPC/ListSettlement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InjectiveRfqRPCServer).ListSettlement(ctx, req.(*ListSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InjectiveRfqRPC_StreamSettlement_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSettlementRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InjectiveRfqRPCServer).StreamSettlement(m, &injectiveRfqRPCStreamSettlementServer{stream})
}

type InjectiveRfqRPC_StreamSettlementServer interface {
	Send(*StreamSettlementResponse) error
	grpc.ServerStream
}

type injectiveRfqRPCStreamSettlementServer struct {
	grpc.ServerStream
}

func (x *injectiveRfqRPCStreamSettlementServer) Send(m *StreamSettlementResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _InjectiveRfqRPC_CreateConditionalOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConditionalOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InjectiveRfqRPCServer).CreateConditionalOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/injective_rfq_rpc.InjectiveRfqRPC/CreateConditionalOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InjectiveRfqRPCServer).CreateConditionalOrder(ctx, req.(*CreateConditionalOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InjectiveRfqRPC_ListConditionalOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConditionalOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InjectiveRfqRPCServer).ListConditionalOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/injective_rfq_rpc.InjectiveRfqRPC/ListConditionalOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InjectiveRfqRPCServer).ListConditionalOrders(ctx, req.(*ListConditionalOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InjectiveRfqRPC_TakerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InjectiveRfqRPCServer).TakerStream(&injectiveRfqRPCTakerStreamServer{stream})
}

type InjectiveRfqRPC_TakerStreamServer interface {
	Send(*TakerStreamResponse) error
	Recv() (*TakerStreamStreamingRequest, error)
	grpc.ServerStream
}

type injectiveRfqRPCTakerStreamServer struct {
	grpc.ServerStream
}

func (x *injectiveRfqRPCTakerStreamServer) Send(m *TakerStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *injectiveRfqRPCTakerStreamServer) Recv() (*TakerStreamStreamingRequest, error) {
	m := new(TakerStreamStreamingRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _InjectiveRfqRPC_MakerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InjectiveRfqRPCServer).MakerStream(&injectiveRfqRPCMakerStreamServer{stream})
}

type InjectiveRfqRPC_MakerStreamServer interface {
	Send(*MakerStreamResponse) error
	Recv() (*MakerStreamStreamingRequest, error)
	grpc.ServerStream
}

type injectiveRfqRPCMakerStreamServer struct {
	grpc.ServerStream
}

func (x *injectiveRfqRPCMakerStreamServer) Send(m *MakerStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *injectiveRfqRPCMakerStreamServer) Recv() (*MakerStreamStreamingRequest, error) {
	m := new(MakerStreamStreamingRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// InjectiveRfqRPC_ServiceDesc is the grpc.ServiceDesc for InjectiveRfqRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InjectiveRfqRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "injective_rfq_rpc.InjectiveRfqRPC",
	HandlerType: (*InjectiveRfqRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _InjectiveRfqRPC_Request_Handler,
		},
		{
			MethodName: "Quote",
			Handler:    _InjectiveRfqRPC_Quote_Handler,
		},
		{
			MethodName: "ListSettlement",
			Handler:    _InjectiveRfqRPC_ListSettlement_Handler,
		},
		{
			MethodName: "CreateConditionalOrder",
			Handler:    _InjectiveRfqRPC_CreateConditionalOrder_Handler,
		},
		{
			MethodName: "ListConditionalOrders",
			Handler:    _InjectiveRfqRPC_ListConditionalOrders_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRequest",
			Handler:       _InjectiveRfqRPC_StreamRequest_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamQuote",
			Handler:       _InjectiveRfqRPC_StreamQuote_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamSettlement",
			Handler:       _InjectiveRfqRPC_StreamSettlement_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TakerStream",
			Handler:       _InjectiveRfqRPC_TakerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "MakerStream",
			Handler:       _InjectiveRfqRPC_MakerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "goadesign_goagen_injective_rfq_rpc.proto",
}
