// Code generated with goa v3.7.0, DO NOT EDIT.
//
// InjectiveRfqRPC protocol buffer definition
//
// Command:
// $ goa gen github.com/InjectiveLabs/injective-indexer/api/design -o ../

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: injective_rfq_rpc.proto

package injective_rfq_rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InjectiveRfqRPC_Request_FullMethodName                = "/injective_rfq_rpc.InjectiveRfqRPC/Request"
	InjectiveRfqRPC_StreamRequest_FullMethodName          = "/injective_rfq_rpc.InjectiveRfqRPC/StreamRequest"
	InjectiveRfqRPC_Quote_FullMethodName                  = "/injective_rfq_rpc.InjectiveRfqRPC/Quote"
	InjectiveRfqRPC_StreamQuote_FullMethodName            = "/injective_rfq_rpc.InjectiveRfqRPC/StreamQuote"
	InjectiveRfqRPC_ListSettlement_FullMethodName         = "/injective_rfq_rpc.InjectiveRfqRPC/ListSettlement"
	InjectiveRfqRPC_StreamSettlement_FullMethodName       = "/injective_rfq_rpc.InjectiveRfqRPC/StreamSettlement"
	InjectiveRfqRPC_CreateConditionalOrder_FullMethodName = "/injective_rfq_rpc.InjectiveRfqRPC/CreateConditionalOrder"
	InjectiveRfqRPC_ListConditionalOrders_FullMethodName  = "/injective_rfq_rpc.InjectiveRfqRPC/ListConditionalOrders"
	InjectiveRfqRPC_TakerStream_FullMethodName            = "/injective_rfq_rpc.InjectiveRfqRPC/TakerStream"
	InjectiveRfqRPC_MakerStream_FullMethodName            = "/injective_rfq_rpc.InjectiveRfqRPC/MakerStream"
)

// InjectiveRfqRPCClient is the client API for InjectiveRfqRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InjectiveRfqRPC defines gRPC API of the RFQ (Request for Quote) API.
type InjectiveRfqRPCClient interface {
	// Create RFQ request
	Request(ctx context.Context, in *RequestRequest, opts ...grpc.CallOption) (*RequestResponse, error)
	// Stream RFQ requests
	StreamRequest(ctx context.Context, in *StreamRequestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamRequestResponse], error)
	// Create RFQ quote
	Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error)
	// Stream RFQ quotes
	StreamQuote(ctx context.Context, in *StreamQuoteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamQuoteResponse], error)
	// List RFQ settlements
	ListSettlement(ctx context.Context, in *ListSettlementRequest, opts ...grpc.CallOption) (*ListSettlementResponse, error)
	// Stream RFQ settlements
	StreamSettlement(ctx context.Context, in *StreamSettlementRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamSettlementResponse], error)
	// Create a conditional TP/SL order
	CreateConditionalOrder(ctx context.Context, in *CreateConditionalOrderRequest, opts ...grpc.CallOption) (*CreateConditionalOrderResponse, error)
	// List conditional TP/SL orders
	ListConditionalOrders(ctx context.Context, in *ListConditionalOrdersRequest, opts ...grpc.CallOption) (*ListConditionalOrdersResponse, error)
	// Bidirectional stream for takers: send requests, receive quotes
	TakerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TakerStreamStreamingRequest, TakerStreamResponse], error)
	// Bidirectional stream for makers: receive requests, send quotes
	MakerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MakerStreamStreamingRequest, MakerStreamResponse], error)
}

type injectiveRfqRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewInjectiveRfqRPCClient(cc grpc.ClientConnInterface) InjectiveRfqRPCClient {
	return &injectiveRfqRPCClient{cc}
}

func (c *injectiveRfqRPCClient) Request(ctx context.Context, in *RequestRequest, opts ...grpc.CallOption) (*RequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestResponse)
	err := c.cc.Invoke(ctx, InjectiveRfqRPC_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *injectiveRfqRPCClient) StreamRequest(ctx context.Context, in *StreamRequestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamRequestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InjectiveRfqRPC_ServiceDesc.Streams[0], InjectiveRfqRPC_StreamRequest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequestRequest, StreamRequestResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InjectiveRfqRPC_StreamRequestClient = grpc.ServerStreamingClient[StreamRequestResponse]

func (c *injectiveRfqRPCClient) Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuoteResponse)
	err := c.cc.Invoke(ctx, InjectiveRfqRPC_Quote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *injectiveRfqRPCClient) StreamQuote(ctx context.Context, in *StreamQuoteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamQuoteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InjectiveRfqRPC_ServiceDesc.Streams[1], InjectiveRfqRPC_StreamQuote_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamQuoteRequest, StreamQuoteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InjectiveRfqRPC_StreamQuoteClient = grpc.ServerStreamingClient[StreamQuoteResponse]

func (c *injectiveRfqRPCClient) ListSettlement(ctx context.Context, in *ListSettlementRequest, opts ...grpc.CallOption) (*ListSettlementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSettlementResponse)
	err := c.cc.Invoke(ctx, InjectiveRfqRPC_ListSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *injectiveRfqRPCClient) StreamSettlement(ctx context.Context, in *StreamSettlementRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamSettlementResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InjectiveRfqRPC_ServiceDesc.Streams[2], InjectiveRfqRPC_StreamSettlement_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSettlementRequest, StreamSettlementResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InjectiveRfqRPC_StreamSettlementClient = grpc.ServerStreamingClient[StreamSettlementResponse]

func (c *injectiveRfqRPCClient) CreateConditionalOrder(ctx context.Context, in *CreateConditionalOrderRequest, opts ...grpc.CallOption) (*CreateConditionalOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateConditionalOrderResponse)
	err := c.cc.Invoke(ctx, InjectiveRfqRPC_CreateConditionalOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *injectiveRfqRPCClient) ListConditionalOrders(ctx context.Context, in *ListConditionalOrdersRequest, opts ...grpc.CallOption) (*ListConditionalOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConditionalOrdersResponse)
	err := c.cc.Invoke(ctx, InjectiveRfqRPC_ListConditionalOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *injectiveRfqRPCClient) TakerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TakerStreamStreamingRequest, TakerStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InjectiveRfqRPC_ServiceDesc.Streams[3], InjectiveRfqRPC_TakerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TakerStreamStreamingRequest, TakerStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InjectiveRfqRPC_TakerStreamClient = grpc.BidiStreamingClient[TakerStreamStreamingRequest, TakerStreamResponse]

func (c *injectiveRfqRPCClient) MakerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MakerStreamStreamingRequest, MakerStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InjectiveRfqRPC_ServiceDesc.Streams[4], InjectiveRfqRPC_MakerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MakerStreamStreamingRequest, MakerStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InjectiveRfqRPC_MakerStreamClient = grpc.BidiStreamingClient[MakerStreamStreamingRequest, MakerStreamResponse]

// InjectiveRfqRPCServer is the server API for InjectiveRfqRPC service.
// All implementations must embed UnimplementedInjectiveRfqRPCServer
// for forward compatibility.
//
// InjectiveRfqRPC defines gRPC API of the RFQ (Request for Quote) API.
type InjectiveRfqRPCServer interface {
	// Create RFQ request
	Request(context.Context, *RequestRequest) (*RequestResponse, error)
	// Stream RFQ requests
	StreamRequest(*StreamRequestRequest, grpc.ServerStreamingServer[StreamRequestResponse]) error
	// Create RFQ quote
	Quote(context.Context, *QuoteRequest) (*QuoteResponse, error)
	// Stream RFQ quotes
	StreamQuote(*StreamQuoteRequest, grpc.ServerStreamingServer[StreamQuoteResponse]) error
	// List RFQ settlements
	ListSettlement(context.Context, *ListSettlementRequest) (*ListSettlementResponse, error)
	// Stream RFQ settlements
	StreamSettlement(*StreamSettlementRequest, grpc.ServerStreamingServer[StreamSettlementResponse]) error
	// Create a conditional TP/SL order
	CreateConditionalOrder(context.Context, *CreateConditionalOrderRequest) (*CreateConditionalOrderResponse, error)
	// List conditional TP/SL orders
	ListConditionalOrders(context.Context, *ListConditionalOrdersRequest) (*ListConditionalOrdersResponse, error)
	// Bidirectional stream for takers: send requests, receive quotes
	TakerStream(grpc.BidiStreamingServer[TakerStreamStreamingRequest, TakerStreamResponse]) error
	// Bidirectional stream for makers: receive requests, send quotes
	MakerStream(grpc.BidiStreamingServer[MakerStreamStreamingRequest, MakerStreamResponse]) error
	mustEmbedUnimplementedInjectiveRfqRPCServer()
}

// UnimplementedInjectiveRfqRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInjectiveRfqRPCServer struct{}

func (UnimplementedInjectiveRfqRPCServer) Request(context.Context, *RequestRequest) (*RequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) StreamRequest(*StreamRequestRequest, grpc.ServerStreamingServer[StreamRequestResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamRequest not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) Quote(context.Context, *QuoteRequest) (*QuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Quote not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) StreamQuote(*StreamQuoteRequest, grpc.ServerStreamingServer[StreamQuoteResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamQuote not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) ListSettlement(context.Context, *ListSettlementRequest) (*ListSettlementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSettlement not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) StreamSettlement(*StreamSettlementRequest, grpc.ServerStreamingServer[StreamSettlementResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamSettlement not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) CreateConditionalOrder(context.Context, *CreateConditionalOrderRequest) (*CreateConditionalOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConditionalOrder not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) ListConditionalOrders(context.Context, *ListConditionalOrdersRequest) (*ListConditionalOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConditionalOrders not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) TakerStream(grpc.BidiStreamingServer[TakerStreamStreamingRequest, TakerStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method TakerStream not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) MakerStream(grpc.BidiStreamingServer[MakerStreamStreamingRequest, MakerStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method MakerStream not implemented")
}
func (UnimplementedInjectiveRfqRPCServer) mustEmbedUnimplementedInjectiveRfqRPCServer() {}
func (UnimplementedInjectiveRfqRPCServer) testEmbeddedByValue()                         {}

// UnsafeInjectiveRfqRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InjectiveRfqRPCServer will
// result in compilation errors.
type UnsafeInjectiveRfqRPCServer interface {
	mustEmbedUnimplementedInjectiveRfqRPCServer()
}

func RegisterInjectiveRfqRPCServer(s grpc.ServiceRegistrar, srv InjectiveRfqRPCServer) {
	// If the following call pancis, it indicates UnimplementedInjectiveRfqRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InjectiveRfqRPC_ServiceDesc, srv)
}

func _InjectiveRfqRPC_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InjectiveRfqRPCServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InjectiveRfqRPC_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InjectiveRfqRPCServer).Request(ctx, req.(*RequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InjectiveRfqRPC_StreamRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequestRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InjectiveRfqRPCServer).StreamRequest(m, &grpc.GenericServerStream[StreamRequestRequest, StreamRequestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InjectiveRfqRPC_StreamRequestServer = grpc.ServerStreamingServer[StreamRequestResponse]

func _InjectiveRfqRPC_Quote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InjectiveRfqRPCServer).Quote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InjectiveRfqRPC_Quote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InjectiveRfqRPCServer).Quote(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InjectiveRfqRPC_StreamQuote_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamQuoteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InjectiveRfqRPCServer).StreamQuote(m, &grpc.GenericServerStream[StreamQuoteRequest, StreamQuoteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InjectiveRfqRPC_StreamQuoteServer = grpc.ServerStreamingServer[StreamQuoteResponse]

func _InjectiveRfqRPC_ListSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InjectiveRfqRPCServer).ListSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InjectiveRfqRPC_ListSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InjectiveRfqRPCServer).ListSettlement(ctx, req.(*ListSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InjectiveRfqRPC_StreamSettlement_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSettlementRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InjectiveRfqRPCServer).StreamSettlement(m, &grpc.GenericServerStream[StreamSettlementRequest, StreamSettlementResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InjectiveRfqRPC_StreamSettlementServer = grpc.ServerStreamingServer[StreamSettlementResponse]

func _InjectiveRfqRPC_CreateConditionalOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConditionalOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InjectiveRfqRPCServer).CreateConditionalOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InjectiveRfqRPC_CreateConditionalOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InjectiveRfqRPCServer).CreateConditionalOrder(ctx, req.(*CreateConditionalOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InjectiveRfqRPC_ListConditionalOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConditionalOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InjectiveRfqRPCServer).ListConditionalOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InjectiveRfqRPC_ListConditionalOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InjectiveRfqRPCServer).ListConditionalOrders(ctx, req.(*ListConditionalOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InjectiveRfqRPC_TakerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InjectiveRfqRPCServer).TakerStream(&grpc.GenericServerStream[TakerStreamStreamingRequest, TakerStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InjectiveRfqRPC_TakerStreamServer = grpc.BidiStreamingServer[TakerStreamStreamingRequest, TakerStreamResponse]

func _InjectiveRfqRPC_MakerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InjectiveRfqRPCServer).MakerStream(&grpc.GenericServerStream[MakerStreamStreamingRequest, MakerStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InjectiveRfqRPC_MakerStreamServer = grpc.BidiStreamingServer[MakerStreamStreamingRequest, MakerStreamResponse]

// InjectiveRfqRPC_ServiceDesc is the grpc.ServiceDesc for InjectiveRfqRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InjectiveRfqRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "injective_rfq_rpc.InjectiveRfqRPC",
	HandlerType: (*InjectiveRfqRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _InjectiveRfqRPC_Request_Handler,
		},
		{
			MethodName: "Quote",
			Handler:    _InjectiveRfqRPC_Quote_Handler,
		},
		{
			MethodName: "ListSettlement",
			Handler:    _InjectiveRfqRPC_ListSettlement_Handler,
		},
		{
			MethodName: "CreateConditionalOrder",
			Handler:    _InjectiveRfqRPC_CreateConditionalOrder_Handler,
		},
		{
			MethodName: "ListConditionalOrders",
			Handler:    _InjectiveRfqRPC_ListConditionalOrders_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRequest",
			Handler:       _InjectiveRfqRPC_StreamRequest_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamQuote",
			Handler:       _InjectiveRfqRPC_StreamQuote_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamSettlement",
			Handler:       _InjectiveRfqRPC_StreamSettlement_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TakerStream",
			Handler:       _InjectiveRfqRPC_TakerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "MakerStream",
			Handler:       _InjectiveRfqRPC_MakerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "injective_rfq_rpc.proto",
}
