// Code generated with goa v3.7.0, DO NOT EDIT.
//
// InjectiveRfqRPC protocol buffer definition
//
// Command:
// $ goa gen github.com/InjectiveLabs/injective-indexer/api/design -o ../

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: injective_rfq_rpc.proto

package injective_rfq_rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFQ request to create
	Request       *RFQRequestInputType `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRequest) Reset() {
	*x = RequestRequest{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRequest) ProtoMessage() {}

func (x *RequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRequest.ProtoReflect.Descriptor instead.
func (*RequestRequest) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RequestRequest) GetRequest() *RFQRequestInputType {
	if x != nil {
		return x.Request
	}
	return nil
}

// RFQ request
type RFQRequestInputType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client ID
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Market ID
	MarketId string `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Direction (long/short)
	Direction string `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	// Margin amount
	Margin string `protobuf:"bytes,4,opt,name=margin,proto3" json:"margin,omitempty"`
	// Quantity
	Quantity string `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Worst acceptable price
	WorstPrice string `protobuf:"bytes,6,opt,name=worst_price,json=worstPrice,proto3" json:"worst_price,omitempty"`
	// Requester address
	RequestAddress string `protobuf:"bytes,7,opt,name=request_address,json=requestAddress,proto3" json:"request_address,omitempty"`
	// Expiry timestamp in milliseconds
	Expiry uint64 `protobuf:"varint,8,opt,name=expiry,proto3" json:"expiry,omitempty"`
	// Transaction time timestamp
	TransactionTime uint64 `protobuf:"varint,9,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RFQRequestInputType) Reset() {
	*x = RFQRequestInputType{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RFQRequestInputType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFQRequestInputType) ProtoMessage() {}

func (x *RFQRequestInputType) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFQRequestInputType.ProtoReflect.Descriptor instead.
func (*RFQRequestInputType) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RFQRequestInputType) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RFQRequestInputType) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *RFQRequestInputType) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *RFQRequestInputType) GetMargin() string {
	if x != nil {
		return x.Margin
	}
	return ""
}

func (x *RFQRequestInputType) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *RFQRequestInputType) GetWorstPrice() string {
	if x != nil {
		return x.WorstPrice
	}
	return ""
}

func (x *RFQRequestInputType) GetRequestAddress() string {
	if x != nil {
		return x.RequestAddress
	}
	return ""
}

func (x *RFQRequestInputType) GetExpiry() uint64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *RFQRequestInputType) GetTransactionTime() uint64 {
	if x != nil {
		return x.TransactionTime
	}
	return 0
}

type RequestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status of the operation
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Client ID
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Generated RFQ ID
	RfqId         uint64 `protobuf:"varint,3,opt,name=rfq_id,json=rfqId,proto3" json:"rfq_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestResponse) Reset() {
	*x = RequestResponse{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestResponse) ProtoMessage() {}

func (x *RequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestResponse.ProtoReflect.Descriptor instead.
func (*RequestResponse) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RequestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RequestResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RequestResponse) GetRfqId() uint64 {
	if x != nil {
		return x.RfqId
	}
	return 0
}

type StreamRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by market IDs
	MarketIds     []string `protobuf:"bytes,1,rep,name=market_ids,json=marketIds,proto3" json:"market_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequestRequest) Reset() {
	*x = StreamRequestRequest{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequestRequest) ProtoMessage() {}

func (x *StreamRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequestRequest.ProtoReflect.Descriptor instead.
func (*StreamRequestRequest) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *StreamRequestRequest) GetMarketIds() []string {
	if x != nil {
		return x.MarketIds
	}
	return nil
}

type StreamRequestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFQ request update
	Request *RFQRequestType `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	// Operation type (insert, update, delete)
	StreamOperation string `protobuf:"bytes,2,opt,name=stream_operation,json=streamOperation,proto3" json:"stream_operation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamRequestResponse) Reset() {
	*x = StreamRequestResponse{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequestResponse) ProtoMessage() {}

func (x *StreamRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequestResponse.ProtoReflect.Descriptor instead.
func (*StreamRequestResponse) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *StreamRequestResponse) GetRequest() *RFQRequestType {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *StreamRequestResponse) GetStreamOperation() string {
	if x != nil {
		return x.StreamOperation
	}
	return ""
}

// RFQ request
type RFQRequestType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client ID
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// RFQ ID
	RfqId uint64 `protobuf:"varint,2,opt,name=rfq_id,json=rfqId,proto3" json:"rfq_id,omitempty"`
	// Market ID
	MarketId string `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Direction (long/short)
	Direction string `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	// Margin amount
	Margin string `protobuf:"bytes,5,opt,name=margin,proto3" json:"margin,omitempty"`
	// Quantity
	Quantity string `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Worst acceptable price
	WorstPrice string `protobuf:"bytes,7,opt,name=worst_price,json=worstPrice,proto3" json:"worst_price,omitempty"`
	// Requester address
	RequestAddress string `protobuf:"bytes,8,opt,name=request_address,json=requestAddress,proto3" json:"request_address,omitempty"`
	// Expiry timestamp in milliseconds
	Expiry uint64 `protobuf:"varint,9,opt,name=expiry,proto3" json:"expiry,omitempty"`
	// Status (open, cancelled, completed)
	Status string `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	// Creation timestamp
	CreatedAt int64 `protobuf:"zigzag64,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt int64 `protobuf:"zigzag64,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Transaction time timestamp
	TransactionTime uint64 `protobuf:"varint,13,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	// Block height
	Height        uint64 `protobuf:"varint,14,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RFQRequestType) Reset() {
	*x = RFQRequestType{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RFQRequestType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFQRequestType) ProtoMessage() {}

func (x *RFQRequestType) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFQRequestType.ProtoReflect.Descriptor instead.
func (*RFQRequestType) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *RFQRequestType) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RFQRequestType) GetRfqId() uint64 {
	if x != nil {
		return x.RfqId
	}
	return 0
}

func (x *RFQRequestType) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *RFQRequestType) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *RFQRequestType) GetMargin() string {
	if x != nil {
		return x.Margin
	}
	return ""
}

func (x *RFQRequestType) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *RFQRequestType) GetWorstPrice() string {
	if x != nil {
		return x.WorstPrice
	}
	return ""
}

func (x *RFQRequestType) GetRequestAddress() string {
	if x != nil {
		return x.RequestAddress
	}
	return ""
}

func (x *RFQRequestType) GetExpiry() uint64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *RFQRequestType) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RFQRequestType) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RFQRequestType) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *RFQRequestType) GetTransactionTime() uint64 {
	if x != nil {
		return x.TransactionTime
	}
	return 0
}

func (x *RFQRequestType) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type QuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFQ quote to create
	Quote         *RFQQuoteType `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *QuoteRequest) GetQuote() *RFQQuoteType {
	if x != nil {
		return x.Quote
	}
	return nil
}

// RFQ quote
type RFQQuoteType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chain ID
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Contract address
	ContractAddress string `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	// Market ID
	MarketId string `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// RFQ ID
	RfqId uint64 `protobuf:"varint,4,opt,name=rfq_id,json=rfqId,proto3" json:"rfq_id,omitempty"`
	// Taker direction (long/short)
	TakerDirection string `protobuf:"bytes,5,opt,name=taker_direction,json=takerDirection,proto3" json:"taker_direction,omitempty"`
	// Margin amount
	Margin string `protobuf:"bytes,6,opt,name=margin,proto3" json:"margin,omitempty"`
	// Quantity
	Quantity string `protobuf:"bytes,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Price
	Price string `protobuf:"bytes,8,opt,name=price,proto3" json:"price,omitempty"`
	// Expiry timestamp and height
	Expiry *RFQExpiryType `protobuf:"bytes,9,opt,name=expiry,proto3" json:"expiry,omitempty"`
	// Maker address
	Maker string `protobuf:"bytes,10,opt,name=maker,proto3" json:"maker,omitempty"`
	// Taker address
	Taker string `protobuf:"bytes,11,opt,name=taker,proto3" json:"taker,omitempty"`
	// Signature
	Signature string `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
	// Status (pending, accepted, rejected, expired)
	Status string `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	// Creation timestamp
	CreatedAt int64 `protobuf:"zigzag64,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt int64 `protobuf:"zigzag64,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Block height
	Height uint64 `protobuf:"varint,16,opt,name=height,proto3" json:"height,omitempty"`
	// Event time timestamp
	EventTime uint64 `protobuf:"varint,17,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	// Transaction time timestamp
	TransactionTime uint64 `protobuf:"varint,18,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	// Maker subaccount nonce used in quote signature
	MakerSubaccountNonce uint64 `protobuf:"varint,19,opt,name=maker_subaccount_nonce,json=makerSubaccountNonce,proto3" json:"maker_subaccount_nonce,omitempty"`
	// Optional minimum fill quantity used in quote signature
	MinFillQuantity string `protobuf:"bytes,20,opt,name=min_fill_quantity,json=minFillQuantity,proto3" json:"min_fill_quantity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RFQQuoteType) Reset() {
	*x = RFQQuoteType{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RFQQuoteType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFQQuoteType) ProtoMessage() {}

func (x *RFQQuoteType) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFQQuoteType.ProtoReflect.Descriptor instead.
func (*RFQQuoteType) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *RFQQuoteType) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *RFQQuoteType) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *RFQQuoteType) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *RFQQuoteType) GetRfqId() uint64 {
	if x != nil {
		return x.RfqId
	}
	return 0
}

func (x *RFQQuoteType) GetTakerDirection() string {
	if x != nil {
		return x.TakerDirection
	}
	return ""
}

func (x *RFQQuoteType) GetMargin() string {
	if x != nil {
		return x.Margin
	}
	return ""
}

func (x *RFQQuoteType) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *RFQQuoteType) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *RFQQuoteType) GetExpiry() *RFQExpiryType {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *RFQQuoteType) GetMaker() string {
	if x != nil {
		return x.Maker
	}
	return ""
}

func (x *RFQQuoteType) GetTaker() string {
	if x != nil {
		return x.Taker
	}
	return ""
}

func (x *RFQQuoteType) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *RFQQuoteType) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RFQQuoteType) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RFQQuoteType) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *RFQQuoteType) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RFQQuoteType) GetEventTime() uint64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

func (x *RFQQuoteType) GetTransactionTime() uint64 {
	if x != nil {
		return x.TransactionTime
	}
	return 0
}

func (x *RFQQuoteType) GetMakerSubaccountNonce() uint64 {
	if x != nil {
		return x.MakerSubaccountNonce
	}
	return 0
}

func (x *RFQQuoteType) GetMinFillQuantity() string {
	if x != nil {
		return x.MinFillQuantity
	}
	return ""
}

// Expiry with timestamp and block height
type RFQExpiryType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expiry timestamp in milliseconds
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Expiry block height
	Height        uint64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RFQExpiryType) Reset() {
	*x = RFQExpiryType{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RFQExpiryType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFQExpiryType) ProtoMessage() {}

func (x *RFQExpiryType) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFQExpiryType.ProtoReflect.Descriptor instead.
func (*RFQExpiryType) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *RFQExpiryType) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RFQExpiryType) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type QuoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status of the operation
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *QuoteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StreamQuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by addresses
	Addresses []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// Filter by market IDs
	MarketIds     []string `protobuf:"bytes,2,rep,name=market_ids,json=marketIds,proto3" json:"market_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamQuoteRequest) Reset() {
	*x = StreamQuoteRequest{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamQuoteRequest) ProtoMessage() {}

func (x *StreamQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamQuoteRequest.ProtoReflect.Descriptor instead.
func (*StreamQuoteRequest) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *StreamQuoteRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *StreamQuoteRequest) GetMarketIds() []string {
	if x != nil {
		return x.MarketIds
	}
	return nil
}

type StreamQuoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFQ quote update
	Quote *RFQProcessedQuoteType `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	// Operation type (insert, update, delete)
	StreamOperation string `protobuf:"bytes,2,opt,name=stream_operation,json=streamOperation,proto3" json:"stream_operation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamQuoteResponse) Reset() {
	*x = StreamQuoteResponse{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamQuoteResponse) ProtoMessage() {}

func (x *StreamQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamQuoteResponse.ProtoReflect.Descriptor instead.
func (*StreamQuoteResponse) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *StreamQuoteResponse) GetQuote() *RFQProcessedQuoteType {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *StreamQuoteResponse) GetStreamOperation() string {
	if x != nil {
		return x.StreamOperation
	}
	return ""
}

// RFQ quote result streamed in real-time
type RFQProcessedQuoteType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error message if quote is rejected
	Error string `protobuf:"bytes,50,opt,name=error,proto3" json:"error,omitempty"`
	// Executed quantity for the quote, if successful
	ExecutedQuantity string `protobuf:"bytes,51,opt,name=executed_quantity,json=executedQuantity,proto3" json:"executed_quantity,omitempty"`
	// Executed margin for the quote, if successful
	ExecutedMargin string `protobuf:"bytes,52,opt,name=executed_margin,json=executedMargin,proto3" json:"executed_margin,omitempty"`
	// Chain ID
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Contract address
	ContractAddress string `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	// Market ID
	MarketId string `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// RFQ ID
	RfqId uint64 `protobuf:"varint,4,opt,name=rfq_id,json=rfqId,proto3" json:"rfq_id,omitempty"`
	// Taker direction (long/short)
	TakerDirection string `protobuf:"bytes,5,opt,name=taker_direction,json=takerDirection,proto3" json:"taker_direction,omitempty"`
	// Margin amount
	Margin string `protobuf:"bytes,6,opt,name=margin,proto3" json:"margin,omitempty"`
	// Quantity
	Quantity string `protobuf:"bytes,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Price
	Price string `protobuf:"bytes,8,opt,name=price,proto3" json:"price,omitempty"`
	// Expiry timestamp and height
	Expiry *RFQExpiryType `protobuf:"bytes,9,opt,name=expiry,proto3" json:"expiry,omitempty"`
	// Maker address
	Maker string `protobuf:"bytes,10,opt,name=maker,proto3" json:"maker,omitempty"`
	// Taker address
	Taker string `protobuf:"bytes,11,opt,name=taker,proto3" json:"taker,omitempty"`
	// Signature
	Signature string `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
	// Status (pending, accepted, rejected, expired)
	Status string `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	// Creation timestamp
	CreatedAt int64 `protobuf:"zigzag64,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt int64 `protobuf:"zigzag64,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Block height
	Height uint64 `protobuf:"varint,16,opt,name=height,proto3" json:"height,omitempty"`
	// Event time timestamp
	EventTime uint64 `protobuf:"varint,17,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	// Transaction time timestamp
	TransactionTime uint64 `protobuf:"varint,18,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	// Maker subaccount nonce used in quote signature
	MakerSubaccountNonce uint64 `protobuf:"varint,19,opt,name=maker_subaccount_nonce,json=makerSubaccountNonce,proto3" json:"maker_subaccount_nonce,omitempty"`
	// Optional minimum fill quantity used in quote signature
	MinFillQuantity string `protobuf:"bytes,20,opt,name=min_fill_quantity,json=minFillQuantity,proto3" json:"min_fill_quantity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RFQProcessedQuoteType) Reset() {
	*x = RFQProcessedQuoteType{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RFQProcessedQuoteType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFQProcessedQuoteType) ProtoMessage() {}

func (x *RFQProcessedQuoteType) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFQProcessedQuoteType.ProtoReflect.Descriptor instead.
func (*RFQProcessedQuoteType) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *RFQProcessedQuoteType) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RFQProcessedQuoteType) GetExecutedQuantity() string {
	if x != nil {
		return x.ExecutedQuantity
	}
	return ""
}

func (x *RFQProcessedQuoteType) GetExecutedMargin() string {
	if x != nil {
		return x.ExecutedMargin
	}
	return ""
}

func (x *RFQProcessedQuoteType) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *RFQProcessedQuoteType) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *RFQProcessedQuoteType) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *RFQProcessedQuoteType) GetRfqId() uint64 {
	if x != nil {
		return x.RfqId
	}
	return 0
}

func (x *RFQProcessedQuoteType) GetTakerDirection() string {
	if x != nil {
		return x.TakerDirection
	}
	return ""
}

func (x *RFQProcessedQuoteType) GetMargin() string {
	if x != nil {
		return x.Margin
	}
	return ""
}

func (x *RFQProcessedQuoteType) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *RFQProcessedQuoteType) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *RFQProcessedQuoteType) GetExpiry() *RFQExpiryType {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *RFQProcessedQuoteType) GetMaker() string {
	if x != nil {
		return x.Maker
	}
	return ""
}

func (x *RFQProcessedQuoteType) GetTaker() string {
	if x != nil {
		return x.Taker
	}
	return ""
}

func (x *RFQProcessedQuoteType) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *RFQProcessedQuoteType) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RFQProcessedQuoteType) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RFQProcessedQuoteType) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *RFQProcessedQuoteType) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RFQProcessedQuoteType) GetEventTime() uint64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

func (x *RFQProcessedQuoteType) GetTransactionTime() uint64 {
	if x != nil {
		return x.TransactionTime
	}
	return 0
}

func (x *RFQProcessedQuoteType) GetMakerSubaccountNonce() uint64 {
	if x != nil {
		return x.MakerSubaccountNonce
	}
	return 0
}

func (x *RFQProcessedQuoteType) GetMinFillQuantity() string {
	if x != nil {
		return x.MinFillQuantity
	}
	return ""
}

type ListSettlementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by taker addresses
	Addresses []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// Number of records per page
	PerPage int32 `protobuf:"zigzag32,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	// Pagination token
	Token         string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSettlementRequest) Reset() {
	*x = ListSettlementRequest{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSettlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSettlementRequest) ProtoMessage() {}

func (x *ListSettlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSettlementRequest.ProtoReflect.Descriptor instead.
func (*ListSettlementRequest) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *ListSettlementRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *ListSettlementRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListSettlementRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ListSettlementResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of RFQ settlements
	Settlements []*RFQSettlementType `protobuf:"bytes,1,rep,name=settlements,proto3" json:"settlements,omitempty"`
	// Next tokens for pagination
	Next          []string `protobuf:"bytes,2,rep,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSettlementResponse) Reset() {
	*x = ListSettlementResponse{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSettlementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSettlementResponse) ProtoMessage() {}

func (x *ListSettlementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSettlementResponse.ProtoReflect.Descriptor instead.
func (*ListSettlementResponse) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *ListSettlementResponse) GetSettlements() []*RFQSettlementType {
	if x != nil {
		return x.Settlements
	}
	return nil
}

func (x *ListSettlementResponse) GetNext() []string {
	if x != nil {
		return x.Next
	}
	return nil
}

// RFQ settlement
type RFQSettlementType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFQ ID
	RfqId uint64 `protobuf:"varint,1,opt,name=rfq_id,json=rfqId,proto3" json:"rfq_id,omitempty"`
	// Market ID
	MarketId string `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Taker address
	Taker string `protobuf:"bytes,3,opt,name=taker,proto3" json:"taker,omitempty"`
	// Direction (long/short)
	Direction string `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	// Margin amount
	Margin string `protobuf:"bytes,5,opt,name=margin,proto3" json:"margin,omitempty"`
	// Quantity
	Quantity string `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Worst acceptable price
	WorstPrice string `protobuf:"bytes,7,opt,name=worst_price,json=worstPrice,proto3" json:"worst_price,omitempty"`
	// Unfilled action details
	UnfilledAction *RFQSettlementUnfilledActionType `protobuf:"bytes,8,opt,name=unfilled_action,json=unfilledAction,proto3" json:"unfilled_action,omitempty"`
	// Fallback quantity
	FallbackQuantity string `protobuf:"bytes,9,opt,name=fallback_quantity,json=fallbackQuantity,proto3" json:"fallback_quantity,omitempty"`
	// Fallback margin
	FallbackMargin string `protobuf:"bytes,10,opt,name=fallback_margin,json=fallbackMargin,proto3" json:"fallback_margin,omitempty"`
	// Transaction time timestamp
	TransactionTime uint64 `protobuf:"varint,11,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	// Creation timestamp
	CreatedAt int64 `protobuf:"zigzag64,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt int64 `protobuf:"zigzag64,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Event time timestamp
	EventTime uint64 `protobuf:"varint,14,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	// Block height
	Height uint64 `protobuf:"varint,15,opt,name=height,proto3" json:"height,omitempty"`
	// Settlement CID
	Cid           string `protobuf:"bytes,16,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RFQSettlementType) Reset() {
	*x = RFQSettlementType{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RFQSettlementType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFQSettlementType) ProtoMessage() {}

func (x *RFQSettlementType) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFQSettlementType.ProtoReflect.Descriptor instead.
func (*RFQSettlementType) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *RFQSettlementType) GetRfqId() uint64 {
	if x != nil {
		return x.RfqId
	}
	return 0
}

func (x *RFQSettlementType) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *RFQSettlementType) GetTaker() string {
	if x != nil {
		return x.Taker
	}
	return ""
}

func (x *RFQSettlementType) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *RFQSettlementType) GetMargin() string {
	if x != nil {
		return x.Margin
	}
	return ""
}

func (x *RFQSettlementType) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *RFQSettlementType) GetWorstPrice() string {
	if x != nil {
		return x.WorstPrice
	}
	return ""
}

func (x *RFQSettlementType) GetUnfilledAction() *RFQSettlementUnfilledActionType {
	if x != nil {
		return x.UnfilledAction
	}
	return nil
}

func (x *RFQSettlementType) GetFallbackQuantity() string {
	if x != nil {
		return x.FallbackQuantity
	}
	return ""
}

func (x *RFQSettlementType) GetFallbackMargin() string {
	if x != nil {
		return x.FallbackMargin
	}
	return ""
}

func (x *RFQSettlementType) GetTransactionTime() uint64 {
	if x != nil {
		return x.TransactionTime
	}
	return 0
}

func (x *RFQSettlementType) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RFQSettlementType) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *RFQSettlementType) GetEventTime() uint64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

func (x *RFQSettlementType) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RFQSettlementType) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

// Action to take for unfilled quantity - only one field should be set
type RFQSettlementUnfilledActionType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Limit order action
	Limit *RFQSettlementLimitActionType `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Market order action
	Market        *RFQSettlementMarketActionType `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RFQSettlementUnfilledActionType) Reset() {
	*x = RFQSettlementUnfilledActionType{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RFQSettlementUnfilledActionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFQSettlementUnfilledActionType) ProtoMessage() {}

func (x *RFQSettlementUnfilledActionType) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFQSettlementUnfilledActionType.ProtoReflect.Descriptor instead.
func (*RFQSettlementUnfilledActionType) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{16}
}

func (x *RFQSettlementUnfilledActionType) GetLimit() *RFQSettlementLimitActionType {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *RFQSettlementUnfilledActionType) GetMarket() *RFQSettlementMarketActionType {
	if x != nil {
		return x.Market
	}
	return nil
}

// Limit order action for unfilled quantity
type RFQSettlementLimitActionType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Limit price
	Price         string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RFQSettlementLimitActionType) Reset() {
	*x = RFQSettlementLimitActionType{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RFQSettlementLimitActionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFQSettlementLimitActionType) ProtoMessage() {}

func (x *RFQSettlementLimitActionType) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFQSettlementLimitActionType.ProtoReflect.Descriptor instead.
func (*RFQSettlementLimitActionType) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{17}
}

func (x *RFQSettlementLimitActionType) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

// Market order action for unfilled quantity
type RFQSettlementMarketActionType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RFQSettlementMarketActionType) Reset() {
	*x = RFQSettlementMarketActionType{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RFQSettlementMarketActionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFQSettlementMarketActionType) ProtoMessage() {}

func (x *RFQSettlementMarketActionType) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFQSettlementMarketActionType.ProtoReflect.Descriptor instead.
func (*RFQSettlementMarketActionType) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{18}
}

type StreamSettlementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by addresses
	Addresses     []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSettlementRequest) Reset() {
	*x = StreamSettlementRequest{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSettlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSettlementRequest) ProtoMessage() {}

func (x *StreamSettlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSettlementRequest.ProtoReflect.Descriptor instead.
func (*StreamSettlementRequest) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{19}
}

func (x *StreamSettlementRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type StreamSettlementResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFQ settlement update
	Settlement *RFQSettlementType `protobuf:"bytes,1,opt,name=settlement,proto3" json:"settlement,omitempty"`
	// Operation type (insert, update, delete)
	StreamOperation string `protobuf:"bytes,2,opt,name=stream_operation,json=streamOperation,proto3" json:"stream_operation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamSettlementResponse) Reset() {
	*x = StreamSettlementResponse{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSettlementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSettlementResponse) ProtoMessage() {}

func (x *StreamSettlementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSettlementResponse.ProtoReflect.Descriptor instead.
func (*StreamSettlementResponse) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{20}
}

func (x *StreamSettlementResponse) GetSettlement() *RFQSettlementType {
	if x != nil {
		return x.Settlement
	}
	return nil
}

func (x *StreamSettlementResponse) GetStreamOperation() string {
	if x != nil {
		return x.StreamOperation
	}
	return ""
}

// Message sent by taker in bidirectional stream
type TakerStreamStreamingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type: 'request', 'ping'
	MessageType string `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	// RFQ request to create
	Request       *CreateRFQRequestType `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakerStreamStreamingRequest) Reset() {
	*x = TakerStreamStreamingRequest{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakerStreamStreamingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakerStreamStreamingRequest) ProtoMessage() {}

func (x *TakerStreamStreamingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakerStreamStreamingRequest.ProtoReflect.Descriptor instead.
func (*TakerStreamStreamingRequest) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{21}
}

func (x *TakerStreamStreamingRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *TakerStreamStreamingRequest) GetRequest() *CreateRFQRequestType {
	if x != nil {
		return x.Request
	}
	return nil
}

// RFQ request
type CreateRFQRequestType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client ID
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Market ID
	MarketId string `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Direction (long/short)
	Direction string `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	// Margin amount
	Margin string `protobuf:"bytes,4,opt,name=margin,proto3" json:"margin,omitempty"`
	// Quantity
	Quantity string `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Worst acceptable price
	WorstPrice string `protobuf:"bytes,6,opt,name=worst_price,json=worstPrice,proto3" json:"worst_price,omitempty"`
	// Expiry timestamp in milliseconds
	Expiry        uint64 `protobuf:"varint,7,opt,name=expiry,proto3" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRFQRequestType) Reset() {
	*x = CreateRFQRequestType{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRFQRequestType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRFQRequestType) ProtoMessage() {}

func (x *CreateRFQRequestType) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRFQRequestType.ProtoReflect.Descriptor instead.
func (*CreateRFQRequestType) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{22}
}

func (x *CreateRFQRequestType) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateRFQRequestType) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *CreateRFQRequestType) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *CreateRFQRequestType) GetMargin() string {
	if x != nil {
		return x.Margin
	}
	return ""
}

func (x *CreateRFQRequestType) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *CreateRFQRequestType) GetWorstPrice() string {
	if x != nil {
		return x.WorstPrice
	}
	return ""
}

func (x *CreateRFQRequestType) GetExpiry() uint64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

type TakerStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type: 'quote', 'request_ack', 'error', 'pong'
	MessageType string `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	// Quote from market maker
	Quote *RFQQuoteType `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	// Acknowledgment for request creation
	RequestAck *RequestStreamAck `protobuf:"bytes,3,opt,name=request_ack,json=requestAck,proto3" json:"request_ack,omitempty"`
	// Error message
	Error         *StreamError `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakerStreamResponse) Reset() {
	*x = TakerStreamResponse{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakerStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakerStreamResponse) ProtoMessage() {}

func (x *TakerStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakerStreamResponse.ProtoReflect.Descriptor instead.
func (*TakerStreamResponse) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{23}
}

func (x *TakerStreamResponse) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *TakerStreamResponse) GetQuote() *RFQQuoteType {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *TakerStreamResponse) GetRequestAck() *RequestStreamAck {
	if x != nil {
		return x.RequestAck
	}
	return nil
}

func (x *TakerStreamResponse) GetError() *StreamError {
	if x != nil {
		return x.Error
	}
	return nil
}

// Acknowledgment for stream operations
type RequestStreamAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFQ ID
	RfqId uint64 `protobuf:"varint,1,opt,name=rfq_id,json=rfqId,proto3" json:"rfq_id,omitempty"`
	// Client ID
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Status of the operation
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestStreamAck) Reset() {
	*x = RequestStreamAck{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestStreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStreamAck) ProtoMessage() {}

func (x *RequestStreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStreamAck.ProtoReflect.Descriptor instead.
func (*RequestStreamAck) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{24}
}

func (x *RequestStreamAck) GetRfqId() uint64 {
	if x != nil {
		return x.RfqId
	}
	return 0
}

func (x *RequestStreamAck) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RequestStreamAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Error message in stream
type StreamError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Error message
	Message_      string `protobuf:"bytes,2,opt,name=message_,json=message,proto3" json:"message_,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamError) Reset() {
	*x = StreamError{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamError) ProtoMessage() {}

func (x *StreamError) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamError.ProtoReflect.Descriptor instead.
func (*StreamError) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{25}
}

func (x *StreamError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StreamError) GetMessage_() string {
	if x != nil {
		return x.Message_
	}
	return ""
}

// Message sent by maker in bidirectional stream
type MakerStreamStreamingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type: 'quote', 'ping'
	MessageType string `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	// Quote to submit
	Quote         *RFQQuoteType `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakerStreamStreamingRequest) Reset() {
	*x = MakerStreamStreamingRequest{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakerStreamStreamingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakerStreamStreamingRequest) ProtoMessage() {}

func (x *MakerStreamStreamingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakerStreamStreamingRequest.ProtoReflect.Descriptor instead.
func (*MakerStreamStreamingRequest) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{26}
}

func (x *MakerStreamStreamingRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *MakerStreamStreamingRequest) GetQuote() *RFQQuoteType {
	if x != nil {
		return x.Quote
	}
	return nil
}

type MakerStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type: 'request', 'quote_ack', 'quote_update', 'settlement_update', 'error',
	// 'pong'
	MessageType string `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	// RFQ request from taker
	Request *RFQRequestType `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	// Acknowledgment for quote submission
	QuoteAck *QuoteStreamAck `protobuf:"bytes,3,opt,name=quote_ack,json=quoteAck,proto3" json:"quote_ack,omitempty"`
	// Error message
	Error *StreamError `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// Processed quote update for maker
	ProcessedQuote *RFQProcessedQuoteType `protobuf:"bytes,5,opt,name=processed_quote,json=processedQuote,proto3" json:"processed_quote,omitempty"`
	// Settlement update for maker
	Settlement    *RFQSettlementMakerUpdate `protobuf:"bytes,6,opt,name=settlement,proto3" json:"settlement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakerStreamResponse) Reset() {
	*x = MakerStreamResponse{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakerStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakerStreamResponse) ProtoMessage() {}

func (x *MakerStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakerStreamResponse.ProtoReflect.Descriptor instead.
func (*MakerStreamResponse) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{27}
}

func (x *MakerStreamResponse) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *MakerStreamResponse) GetRequest() *RFQRequestType {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *MakerStreamResponse) GetQuoteAck() *QuoteStreamAck {
	if x != nil {
		return x.QuoteAck
	}
	return nil
}

func (x *MakerStreamResponse) GetError() *StreamError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *MakerStreamResponse) GetProcessedQuote() *RFQProcessedQuoteType {
	if x != nil {
		return x.ProcessedQuote
	}
	return nil
}

func (x *MakerStreamResponse) GetSettlement() *RFQSettlementMakerUpdate {
	if x != nil {
		return x.Settlement
	}
	return nil
}

// Acknowledgment for stream operations
type QuoteStreamAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFQ ID
	RfqId uint64 `protobuf:"varint,1,opt,name=rfq_id,json=rfqId,proto3" json:"rfq_id,omitempty"`
	// Status of the operation
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteStreamAck) Reset() {
	*x = QuoteStreamAck{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteStreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteStreamAck) ProtoMessage() {}

func (x *QuoteStreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteStreamAck.ProtoReflect.Descriptor instead.
func (*QuoteStreamAck) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{28}
}

func (x *QuoteStreamAck) GetRfqId() uint64 {
	if x != nil {
		return x.RfqId
	}
	return 0
}

func (x *QuoteStreamAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// RFQ settlement update streamed to maker in real-time
type RFQSettlementMakerUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of quotes considered for settlement
	Quotes []*RFQSettlementQuote `protobuf:"bytes,50,rep,name=quotes,proto3" json:"quotes,omitempty"`
	// RFQ ID
	RfqId uint64 `protobuf:"varint,1,opt,name=rfq_id,json=rfqId,proto3" json:"rfq_id,omitempty"`
	// Market ID
	MarketId string `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Taker address
	Taker string `protobuf:"bytes,3,opt,name=taker,proto3" json:"taker,omitempty"`
	// Direction (long/short)
	Direction string `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	// Margin amount
	Margin string `protobuf:"bytes,5,opt,name=margin,proto3" json:"margin,omitempty"`
	// Quantity
	Quantity string `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Worst acceptable price
	WorstPrice string `protobuf:"bytes,7,opt,name=worst_price,json=worstPrice,proto3" json:"worst_price,omitempty"`
	// Unfilled action details
	UnfilledAction *RFQSettlementUnfilledActionType `protobuf:"bytes,8,opt,name=unfilled_action,json=unfilledAction,proto3" json:"unfilled_action,omitempty"`
	// Fallback quantity
	FallbackQuantity string `protobuf:"bytes,9,opt,name=fallback_quantity,json=fallbackQuantity,proto3" json:"fallback_quantity,omitempty"`
	// Fallback margin
	FallbackMargin string `protobuf:"bytes,10,opt,name=fallback_margin,json=fallbackMargin,proto3" json:"fallback_margin,omitempty"`
	// Transaction time timestamp
	TransactionTime uint64 `protobuf:"varint,11,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	// Creation timestamp
	CreatedAt int64 `protobuf:"zigzag64,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt int64 `protobuf:"zigzag64,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Event time timestamp
	EventTime uint64 `protobuf:"varint,14,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	// Block height
	Height uint64 `protobuf:"varint,15,opt,name=height,proto3" json:"height,omitempty"`
	// Settlement CID
	Cid           string `protobuf:"bytes,16,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RFQSettlementMakerUpdate) Reset() {
	*x = RFQSettlementMakerUpdate{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RFQSettlementMakerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFQSettlementMakerUpdate) ProtoMessage() {}

func (x *RFQSettlementMakerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFQSettlementMakerUpdate.ProtoReflect.Descriptor instead.
func (*RFQSettlementMakerUpdate) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{29}
}

func (x *RFQSettlementMakerUpdate) GetQuotes() []*RFQSettlementQuote {
	if x != nil {
		return x.Quotes
	}
	return nil
}

func (x *RFQSettlementMakerUpdate) GetRfqId() uint64 {
	if x != nil {
		return x.RfqId
	}
	return 0
}

func (x *RFQSettlementMakerUpdate) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *RFQSettlementMakerUpdate) GetTaker() string {
	if x != nil {
		return x.Taker
	}
	return ""
}

func (x *RFQSettlementMakerUpdate) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *RFQSettlementMakerUpdate) GetMargin() string {
	if x != nil {
		return x.Margin
	}
	return ""
}

func (x *RFQSettlementMakerUpdate) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *RFQSettlementMakerUpdate) GetWorstPrice() string {
	if x != nil {
		return x.WorstPrice
	}
	return ""
}

func (x *RFQSettlementMakerUpdate) GetUnfilledAction() *RFQSettlementUnfilledActionType {
	if x != nil {
		return x.UnfilledAction
	}
	return nil
}

func (x *RFQSettlementMakerUpdate) GetFallbackQuantity() string {
	if x != nil {
		return x.FallbackQuantity
	}
	return ""
}

func (x *RFQSettlementMakerUpdate) GetFallbackMargin() string {
	if x != nil {
		return x.FallbackMargin
	}
	return ""
}

func (x *RFQSettlementMakerUpdate) GetTransactionTime() uint64 {
	if x != nil {
		return x.TransactionTime
	}
	return 0
}

func (x *RFQSettlementMakerUpdate) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RFQSettlementMakerUpdate) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *RFQSettlementMakerUpdate) GetEventTime() uint64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

func (x *RFQSettlementMakerUpdate) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RFQSettlementMakerUpdate) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

// Quote data embedded in settlement
type RFQSettlementQuote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maker address
	Maker string `protobuf:"bytes,1,opt,name=maker,proto3" json:"maker,omitempty"`
	// Price
	Price string `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	// Quoted margin amount
	QuotedMargin string `protobuf:"bytes,3,opt,name=quoted_margin,json=quotedMargin,proto3" json:"quoted_margin,omitempty"`
	// Quoted quantity
	QuotedQuantity string `protobuf:"bytes,4,opt,name=quoted_quantity,json=quotedQuantity,proto3" json:"quoted_quantity,omitempty"`
	// Executed margin amount
	ExecutedMargin string `protobuf:"bytes,5,opt,name=executed_margin,json=executedMargin,proto3" json:"executed_margin,omitempty"`
	// Executed quantity
	ExecutedQuantity string `protobuf:"bytes,6,opt,name=executed_quantity,json=executedQuantity,proto3" json:"executed_quantity,omitempty"`
	// Expiry timestamp and height
	Expiry *RFQExpiryType `protobuf:"bytes,7,opt,name=expiry,proto3" json:"expiry,omitempty"`
	// Signature
	Signature string `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	// Nonce
	Nonce uint64 `protobuf:"varint,9,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Quote status (accepted, rejected, expired)
	Status        string `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RFQSettlementQuote) Reset() {
	*x = RFQSettlementQuote{}
	mi := &file_injective_rfq_rpc_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RFQSettlementQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFQSettlementQuote) ProtoMessage() {}

func (x *RFQSettlementQuote) ProtoReflect() protoreflect.Message {
	mi := &file_injective_rfq_rpc_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFQSettlementQuote.ProtoReflect.Descriptor instead.
func (*RFQSettlementQuote) Descriptor() ([]byte, []int) {
	return file_injective_rfq_rpc_proto_rawDescGZIP(), []int{30}
}

func (x *RFQSettlementQuote) GetMaker() string {
	if x != nil {
		return x.Maker
	}
	return ""
}

func (x *RFQSettlementQuote) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *RFQSettlementQuote) GetQuotedMargin() string {
	if x != nil {
		return x.QuotedMargin
	}
	return ""
}

func (x *RFQSettlementQuote) GetQuotedQuantity() string {
	if x != nil {
		return x.QuotedQuantity
	}
	return ""
}

func (x *RFQSettlementQuote) GetExecutedMargin() string {
	if x != nil {
		return x.ExecutedMargin
	}
	return ""
}

func (x *RFQSettlementQuote) GetExecutedQuantity() string {
	if x != nil {
		return x.ExecutedQuantity
	}
	return ""
}

func (x *RFQSettlementQuote) GetExpiry() *RFQExpiryType {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *RFQSettlementQuote) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *RFQSettlementQuote) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *RFQSettlementQuote) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_injective_rfq_rpc_proto protoreflect.FileDescriptor

const file_injective_rfq_rpc_proto_rawDesc = "" +
	"\n" +
	"\x17injective_rfq_rpc.proto\x12\x11injective_rfq_rpc\"R\n" +
	"\x0eRequestRequest\x12@\n" +
	"\arequest\x18\x01 \x01(\v2&.injective_rfq_rpc.RFQRequestInputTypeR\arequest\"\xae\x02\n" +
	"\x13RFQRequestInputType\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\tR\bmarketId\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12\x16\n" +
	"\x06margin\x18\x04 \x01(\tR\x06margin\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\tR\bquantity\x12\x1f\n" +
	"\vworst_price\x18\x06 \x01(\tR\n" +
	"worstPrice\x12'\n" +
	"\x0frequest_address\x18\a \x01(\tR\x0erequestAddress\x12\x16\n" +
	"\x06expiry\x18\b \x01(\x04R\x06expiry\x12)\n" +
	"\x10transaction_time\x18\t \x01(\x04R\x0ftransactionTime\"]\n" +
	"\x0fRequestResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x15\n" +
	"\x06rfq_id\x18\x03 \x01(\x04R\x05rfqId\"5\n" +
	"\x14StreamRequestRequest\x12\x1d\n" +
	"\n" +
	"market_ids\x18\x01 \x03(\tR\tmarketIds\"\x7f\n" +
	"\x15StreamRequestResponse\x12;\n" +
	"\arequest\x18\x01 \x01(\v2!.injective_rfq_rpc.RFQRequestTypeR\arequest\x12)\n" +
	"\x10stream_operation\x18\x02 \x01(\tR\x0fstreamOperation\"\xae\x03\n" +
	"\x0eRFQRequestType\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x15\n" +
	"\x06rfq_id\x18\x02 \x01(\x04R\x05rfqId\x12\x1b\n" +
	"\tmarket_id\x18\x03 \x01(\tR\bmarketId\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x16\n" +
	"\x06margin\x18\x05 \x01(\tR\x06margin\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\tR\bquantity\x12\x1f\n" +
	"\vworst_price\x18\a \x01(\tR\n" +
	"worstPrice\x12'\n" +
	"\x0frequest_address\x18\b \x01(\tR\x0erequestAddress\x12\x16\n" +
	"\x06expiry\x18\t \x01(\x04R\x06expiry\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x12R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x12R\tupdatedAt\x12)\n" +
	"\x10transaction_time\x18\r \x01(\x04R\x0ftransactionTime\x12\x16\n" +
	"\x06height\x18\x0e \x01(\x04R\x06height\"E\n" +
	"\fQuoteRequest\x125\n" +
	"\x05quote\x18\x01 \x01(\v2\x1f.injective_rfq_rpc.RFQQuoteTypeR\x05quote\"\x99\x05\n" +
	"\fRFQQuoteType\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12\x1b\n" +
	"\tmarket_id\x18\x03 \x01(\tR\bmarketId\x12\x15\n" +
	"\x06rfq_id\x18\x04 \x01(\x04R\x05rfqId\x12'\n" +
	"\x0ftaker_direction\x18\x05 \x01(\tR\x0etakerDirection\x12\x16\n" +
	"\x06margin\x18\x06 \x01(\tR\x06margin\x12\x1a\n" +
	"\bquantity\x18\a \x01(\tR\bquantity\x12\x14\n" +
	"\x05price\x18\b \x01(\tR\x05price\x128\n" +
	"\x06expiry\x18\t \x01(\v2 .injective_rfq_rpc.RFQExpiryTypeR\x06expiry\x12\x14\n" +
	"\x05maker\x18\n" +
	" \x01(\tR\x05maker\x12\x14\n" +
	"\x05taker\x18\v \x01(\tR\x05taker\x12\x1c\n" +
	"\tsignature\x18\f \x01(\tR\tsignature\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\x12R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\x12R\tupdatedAt\x12\x16\n" +
	"\x06height\x18\x10 \x01(\x04R\x06height\x12\x1d\n" +
	"\n" +
	"event_time\x18\x11 \x01(\x04R\teventTime\x12)\n" +
	"\x10transaction_time\x18\x12 \x01(\x04R\x0ftransactionTime\x124\n" +
	"\x16maker_subaccount_nonce\x18\x13 \x01(\x04R\x14makerSubaccountNonce\x12*\n" +
	"\x11min_fill_quantity\x18\x14 \x01(\tR\x0fminFillQuantity\"E\n" +
	"\rRFQExpiryType\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\"'\n" +
	"\rQuoteResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"Q\n" +
	"\x12StreamQuoteRequest\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x12\x1d\n" +
	"\n" +
	"market_ids\x18\x02 \x03(\tR\tmarketIds\"\x80\x01\n" +
	"\x13StreamQuoteResponse\x12>\n" +
	"\x05quote\x18\x01 \x01(\v2(.injective_rfq_rpc.RFQProcessedQuoteTypeR\x05quote\x12)\n" +
	"\x10stream_operation\x18\x02 \x01(\tR\x0fstreamOperation\"\x8e\x06\n" +
	"\x15RFQProcessedQuoteType\x12\x14\n" +
	"\x05error\x182 \x01(\tR\x05error\x12+\n" +
	"\x11executed_quantity\x183 \x01(\tR\x10executedQuantity\x12'\n" +
	"\x0fexecuted_margin\x184 \x01(\tR\x0eexecutedMargin\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12\x1b\n" +
	"\tmarket_id\x18\x03 \x01(\tR\bmarketId\x12\x15\n" +
	"\x06rfq_id\x18\x04 \x01(\x04R\x05rfqId\x12'\n" +
	"\x0ftaker_direction\x18\x05 \x01(\tR\x0etakerDirection\x12\x16\n" +
	"\x06margin\x18\x06 \x01(\tR\x06margin\x12\x1a\n" +
	"\bquantity\x18\a \x01(\tR\bquantity\x12\x14\n" +
	"\x05price\x18\b \x01(\tR\x05price\x128\n" +
	"\x06expiry\x18\t \x01(\v2 .injective_rfq_rpc.RFQExpiryTypeR\x06expiry\x12\x14\n" +
	"\x05maker\x18\n" +
	" \x01(\tR\x05maker\x12\x14\n" +
	"\x05taker\x18\v \x01(\tR\x05taker\x12\x1c\n" +
	"\tsignature\x18\f \x01(\tR\tsignature\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\x12R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\x12R\tupdatedAt\x12\x16\n" +
	"\x06height\x18\x10 \x01(\x04R\x06height\x12\x1d\n" +
	"\n" +
	"event_time\x18\x11 \x01(\x04R\teventTime\x12)\n" +
	"\x10transaction_time\x18\x12 \x01(\x04R\x0ftransactionTime\x124\n" +
	"\x16maker_subaccount_nonce\x18\x13 \x01(\x04R\x14makerSubaccountNonce\x12*\n" +
	"\x11min_fill_quantity\x18\x14 \x01(\tR\x0fminFillQuantity\"f\n" +
	"\x15ListSettlementRequest\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x11R\aperPage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"t\n" +
	"\x16ListSettlementResponse\x12F\n" +
	"\vsettlements\x18\x01 \x03(\v2$.injective_rfq_rpc.RFQSettlementTypeR\vsettlements\x12\x12\n" +
	"\x04next\x18\x02 \x03(\tR\x04next\"\xb5\x04\n" +
	"\x11RFQSettlementType\x12\x15\n" +
	"\x06rfq_id\x18\x01 \x01(\x04R\x05rfqId\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\tR\bmarketId\x12\x14\n" +
	"\x05taker\x18\x03 \x01(\tR\x05taker\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x16\n" +
	"\x06margin\x18\x05 \x01(\tR\x06margin\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\tR\bquantity\x12\x1f\n" +
	"\vworst_price\x18\a \x01(\tR\n" +
	"worstPrice\x12[\n" +
	"\x0funfilled_action\x18\b \x01(\v22.injective_rfq_rpc.RFQSettlementUnfilledActionTypeR\x0eunfilledAction\x12+\n" +
	"\x11fallback_quantity\x18\t \x01(\tR\x10fallbackQuantity\x12'\n" +
	"\x0ffallback_margin\x18\n" +
	" \x01(\tR\x0efallbackMargin\x12)\n" +
	"\x10transaction_time\x18\v \x01(\x04R\x0ftransactionTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x12R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\x12R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"event_time\x18\x0e \x01(\x04R\teventTime\x12\x16\n" +
	"\x06height\x18\x0f \x01(\x04R\x06height\x12\x10\n" +
	"\x03cid\x18\x10 \x01(\tR\x03cid\"\xb2\x01\n" +
	"\x1fRFQSettlementUnfilledActionType\x12E\n" +
	"\x05limit\x18\x01 \x01(\v2/.injective_rfq_rpc.RFQSettlementLimitActionTypeR\x05limit\x12H\n" +
	"\x06market\x18\x02 \x01(\v20.injective_rfq_rpc.RFQSettlementMarketActionTypeR\x06market\"4\n" +
	"\x1cRFQSettlementLimitActionType\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\"\x1f\n" +
	"\x1dRFQSettlementMarketActionType\"7\n" +
	"\x17StreamSettlementRequest\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\"\x8b\x01\n" +
	"\x18StreamSettlementResponse\x12D\n" +
	"\n" +
	"settlement\x18\x01 \x01(\v2$.injective_rfq_rpc.RFQSettlementTypeR\n" +
	"settlement\x12)\n" +
	"\x10stream_operation\x18\x02 \x01(\tR\x0fstreamOperation\"\x83\x01\n" +
	"\x1bTakerStreamStreamingRequest\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12A\n" +
	"\arequest\x18\x02 \x01(\v2'.injective_rfq_rpc.CreateRFQRequestTypeR\arequest\"\xdb\x01\n" +
	"\x14CreateRFQRequestType\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\tR\bmarketId\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12\x16\n" +
	"\x06margin\x18\x04 \x01(\tR\x06margin\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\tR\bquantity\x12\x1f\n" +
	"\vworst_price\x18\x06 \x01(\tR\n" +
	"worstPrice\x12\x16\n" +
	"\x06expiry\x18\a \x01(\x04R\x06expiry\"\xeb\x01\n" +
	"\x13TakerStreamResponse\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x125\n" +
	"\x05quote\x18\x02 \x01(\v2\x1f.injective_rfq_rpc.RFQQuoteTypeR\x05quote\x12D\n" +
	"\vrequest_ack\x18\x03 \x01(\v2#.injective_rfq_rpc.RequestStreamAckR\n" +
	"requestAck\x124\n" +
	"\x05error\x18\x04 \x01(\v2\x1e.injective_rfq_rpc.StreamErrorR\x05error\"^\n" +
	"\x10RequestStreamAck\x12\x15\n" +
	"\x06rfq_id\x18\x01 \x01(\x04R\x05rfqId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"<\n" +
	"\vStreamError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x19\n" +
	"\bmessage_\x18\x02 \x01(\tR\amessage\"w\n" +
	"\x1bMakerStreamStreamingRequest\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x125\n" +
	"\x05quote\x18\x02 \x01(\v2\x1f.injective_rfq_rpc.RFQQuoteTypeR\x05quote\"\x8b\x03\n" +
	"\x13MakerStreamResponse\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12;\n" +
	"\arequest\x18\x02 \x01(\v2!.injective_rfq_rpc.RFQRequestTypeR\arequest\x12>\n" +
	"\tquote_ack\x18\x03 \x01(\v2!.injective_rfq_rpc.QuoteStreamAckR\bquoteAck\x124\n" +
	"\x05error\x18\x04 \x01(\v2\x1e.injective_rfq_rpc.StreamErrorR\x05error\x12Q\n" +
	"\x0fprocessed_quote\x18\x05 \x01(\v2(.injective_rfq_rpc.RFQProcessedQuoteTypeR\x0eprocessedQuote\x12K\n" +
	"\n" +
	"settlement\x18\x06 \x01(\v2+.injective_rfq_rpc.RFQSettlementMakerUpdateR\n" +
	"settlement\"?\n" +
	"\x0eQuoteStreamAck\x12\x15\n" +
	"\x06rfq_id\x18\x01 \x01(\x04R\x05rfqId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xfb\x04\n" +
	"\x18RFQSettlementMakerUpdate\x12=\n" +
	"\x06quotes\x182 \x03(\v2%.injective_rfq_rpc.RFQSettlementQuoteR\x06quotes\x12\x15\n" +
	"\x06rfq_id\x18\x01 \x01(\x04R\x05rfqId\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\tR\bmarketId\x12\x14\n" +
	"\x05taker\x18\x03 \x01(\tR\x05taker\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x16\n" +
	"\x06margin\x18\x05 \x01(\tR\x06margin\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\tR\bquantity\x12\x1f\n" +
	"\vworst_price\x18\a \x01(\tR\n" +
	"worstPrice\x12[\n" +
	"\x0funfilled_action\x18\b \x01(\v22.injective_rfq_rpc.RFQSettlementUnfilledActionTypeR\x0eunfilledAction\x12+\n" +
	"\x11fallback_quantity\x18\t \x01(\tR\x10fallbackQuantity\x12'\n" +
	"\x0ffallback_margin\x18\n" +
	" \x01(\tR\x0efallbackMargin\x12)\n" +
	"\x10transaction_time\x18\v \x01(\x04R\x0ftransactionTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x12R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\x12R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"event_time\x18\x0e \x01(\x04R\teventTime\x12\x16\n" +
	"\x06height\x18\x0f \x01(\x04R\x06height\x12\x10\n" +
	"\x03cid\x18\x10 \x01(\tR\x03cid\"\xea\x02\n" +
	"\x12RFQSettlementQuote\x12\x14\n" +
	"\x05maker\x18\x01 \x01(\tR\x05maker\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12#\n" +
	"\rquoted_margin\x18\x03 \x01(\tR\fquotedMargin\x12'\n" +
	"\x0fquoted_quantity\x18\x04 \x01(\tR\x0equotedQuantity\x12'\n" +
	"\x0fexecuted_margin\x18\x05 \x01(\tR\x0eexecutedMargin\x12+\n" +
	"\x11executed_quantity\x18\x06 \x01(\tR\x10executedQuantity\x128\n" +
	"\x06expiry\x18\a \x01(\v2 .injective_rfq_rpc.RFQExpiryTypeR\x06expiry\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\x12\x14\n" +
	"\x05nonce\x18\t \x01(\x04R\x05nonce\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status2\xa1\x06\n" +
	"\x0fInjectiveRfqRPC\x12P\n" +
	"\aRequest\x12!.injective_rfq_rpc.RequestRequest\x1a\".injective_rfq_rpc.RequestResponse\x12d\n" +
	"\rStreamRequest\x12'.injective_rfq_rpc.StreamRequestRequest\x1a(.injective_rfq_rpc.StreamRequestResponse0\x01\x12J\n" +
	"\x05Quote\x12\x1f.injective_rfq_rpc.QuoteRequest\x1a .injective_rfq_rpc.QuoteResponse\x12^\n" +
	"\vStreamQuote\x12%.injective_rfq_rpc.StreamQuoteRequest\x1a&.injective_rfq_rpc.StreamQuoteResponse0\x01\x12e\n" +
	"\x0eListSettlement\x12(.injective_rfq_rpc.ListSettlementRequest\x1a).injective_rfq_rpc.ListSettlementResponse\x12m\n" +
	"\x10StreamSettlement\x12*.injective_rfq_rpc.StreamSettlementRequest\x1a+.injective_rfq_rpc.StreamSettlementResponse0\x01\x12i\n" +
	"\vTakerStream\x12..injective_rfq_rpc.TakerStreamStreamingRequest\x1a&.injective_rfq_rpc.TakerStreamResponse(\x010\x01\x12i\n" +
	"\vMakerStream\x12..injective_rfq_rpc.MakerStreamStreamingRequest\x1a&.injective_rfq_rpc.MakerStreamResponse(\x010\x01B\x16Z\x14/injective_rfq_rpcpbb\x06proto3"

var (
	file_injective_rfq_rpc_proto_rawDescOnce sync.Once
	file_injective_rfq_rpc_proto_rawDescData []byte
)

func file_injective_rfq_rpc_proto_rawDescGZIP() []byte {
	file_injective_rfq_rpc_proto_rawDescOnce.Do(func() {
		file_injective_rfq_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_injective_rfq_rpc_proto_rawDesc), len(file_injective_rfq_rpc_proto_rawDesc)))
	})
	return file_injective_rfq_rpc_proto_rawDescData
}

var file_injective_rfq_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_injective_rfq_rpc_proto_goTypes = []any{
	(*RequestRequest)(nil),                  // 0: injective_rfq_rpc.RequestRequest
	(*RFQRequestInputType)(nil),             // 1: injective_rfq_rpc.RFQRequestInputType
	(*RequestResponse)(nil),                 // 2: injective_rfq_rpc.RequestResponse
	(*StreamRequestRequest)(nil),            // 3: injective_rfq_rpc.StreamRequestRequest
	(*StreamRequestResponse)(nil),           // 4: injective_rfq_rpc.StreamRequestResponse
	(*RFQRequestType)(nil),                  // 5: injective_rfq_rpc.RFQRequestType
	(*QuoteRequest)(nil),                    // 6: injective_rfq_rpc.QuoteRequest
	(*RFQQuoteType)(nil),                    // 7: injective_rfq_rpc.RFQQuoteType
	(*RFQExpiryType)(nil),                   // 8: injective_rfq_rpc.RFQExpiryType
	(*QuoteResponse)(nil),                   // 9: injective_rfq_rpc.QuoteResponse
	(*StreamQuoteRequest)(nil),              // 10: injective_rfq_rpc.StreamQuoteRequest
	(*StreamQuoteResponse)(nil),             // 11: injective_rfq_rpc.StreamQuoteResponse
	(*RFQProcessedQuoteType)(nil),           // 12: injective_rfq_rpc.RFQProcessedQuoteType
	(*ListSettlementRequest)(nil),           // 13: injective_rfq_rpc.ListSettlementRequest
	(*ListSettlementResponse)(nil),          // 14: injective_rfq_rpc.ListSettlementResponse
	(*RFQSettlementType)(nil),               // 15: injective_rfq_rpc.RFQSettlementType
	(*RFQSettlementUnfilledActionType)(nil), // 16: injective_rfq_rpc.RFQSettlementUnfilledActionType
	(*RFQSettlementLimitActionType)(nil),    // 17: injective_rfq_rpc.RFQSettlementLimitActionType
	(*RFQSettlementMarketActionType)(nil),   // 18: injective_rfq_rpc.RFQSettlementMarketActionType
	(*StreamSettlementRequest)(nil),         // 19: injective_rfq_rpc.StreamSettlementRequest
	(*StreamSettlementResponse)(nil),        // 20: injective_rfq_rpc.StreamSettlementResponse
	(*TakerStreamStreamingRequest)(nil),     // 21: injective_rfq_rpc.TakerStreamStreamingRequest
	(*CreateRFQRequestType)(nil),            // 22: injective_rfq_rpc.CreateRFQRequestType
	(*TakerStreamResponse)(nil),             // 23: injective_rfq_rpc.TakerStreamResponse
	(*RequestStreamAck)(nil),                // 24: injective_rfq_rpc.RequestStreamAck
	(*StreamError)(nil),                     // 25: injective_rfq_rpc.StreamError
	(*MakerStreamStreamingRequest)(nil),     // 26: injective_rfq_rpc.MakerStreamStreamingRequest
	(*MakerStreamResponse)(nil),             // 27: injective_rfq_rpc.MakerStreamResponse
	(*QuoteStreamAck)(nil),                  // 28: injective_rfq_rpc.QuoteStreamAck
	(*RFQSettlementMakerUpdate)(nil),        // 29: injective_rfq_rpc.RFQSettlementMakerUpdate
	(*RFQSettlementQuote)(nil),              // 30: injective_rfq_rpc.RFQSettlementQuote
}
var file_injective_rfq_rpc_proto_depIdxs = []int32{
	1,  // 0: injective_rfq_rpc.RequestRequest.request:type_name -> injective_rfq_rpc.RFQRequestInputType
	5,  // 1: injective_rfq_rpc.StreamRequestResponse.request:type_name -> injective_rfq_rpc.RFQRequestType
	7,  // 2: injective_rfq_rpc.QuoteRequest.quote:type_name -> injective_rfq_rpc.RFQQuoteType
	8,  // 3: injective_rfq_rpc.RFQQuoteType.expiry:type_name -> injective_rfq_rpc.RFQExpiryType
	12, // 4: injective_rfq_rpc.StreamQuoteResponse.quote:type_name -> injective_rfq_rpc.RFQProcessedQuoteType
	8,  // 5: injective_rfq_rpc.RFQProcessedQuoteType.expiry:type_name -> injective_rfq_rpc.RFQExpiryType
	15, // 6: injective_rfq_rpc.ListSettlementResponse.settlements:type_name -> injective_rfq_rpc.RFQSettlementType
	16, // 7: injective_rfq_rpc.RFQSettlementType.unfilled_action:type_name -> injective_rfq_rpc.RFQSettlementUnfilledActionType
	17, // 8: injective_rfq_rpc.RFQSettlementUnfilledActionType.limit:type_name -> injective_rfq_rpc.RFQSettlementLimitActionType
	18, // 9: injective_rfq_rpc.RFQSettlementUnfilledActionType.market:type_name -> injective_rfq_rpc.RFQSettlementMarketActionType
	15, // 10: injective_rfq_rpc.StreamSettlementResponse.settlement:type_name -> injective_rfq_rpc.RFQSettlementType
	22, // 11: injective_rfq_rpc.TakerStreamStreamingRequest.request:type_name -> injective_rfq_rpc.CreateRFQRequestType
	7,  // 12: injective_rfq_rpc.TakerStreamResponse.quote:type_name -> injective_rfq_rpc.RFQQuoteType
	24, // 13: injective_rfq_rpc.TakerStreamResponse.request_ack:type_name -> injective_rfq_rpc.RequestStreamAck
	25, // 14: injective_rfq_rpc.TakerStreamResponse.error:type_name -> injective_rfq_rpc.StreamError
	7,  // 15: injective_rfq_rpc.MakerStreamStreamingRequest.quote:type_name -> injective_rfq_rpc.RFQQuoteType
	5,  // 16: injective_rfq_rpc.MakerStreamResponse.request:type_name -> injective_rfq_rpc.RFQRequestType
	28, // 17: injective_rfq_rpc.MakerStreamResponse.quote_ack:type_name -> injective_rfq_rpc.QuoteStreamAck
	25, // 18: injective_rfq_rpc.MakerStreamResponse.error:type_name -> injective_rfq_rpc.StreamError
	12, // 19: injective_rfq_rpc.MakerStreamResponse.processed_quote:type_name -> injective_rfq_rpc.RFQProcessedQuoteType
	29, // 20: injective_rfq_rpc.MakerStreamResponse.settlement:type_name -> injective_rfq_rpc.RFQSettlementMakerUpdate
	30, // 21: injective_rfq_rpc.RFQSettlementMakerUpdate.quotes:type_name -> injective_rfq_rpc.RFQSettlementQuote
	16, // 22: injective_rfq_rpc.RFQSettlementMakerUpdate.unfilled_action:type_name -> injective_rfq_rpc.RFQSettlementUnfilledActionType
	8,  // 23: injective_rfq_rpc.RFQSettlementQuote.expiry:type_name -> injective_rfq_rpc.RFQExpiryType
	0,  // 24: injective_rfq_rpc.InjectiveRfqRPC.Request:input_type -> injective_rfq_rpc.RequestRequest
	3,  // 25: injective_rfq_rpc.InjectiveRfqRPC.StreamRequest:input_type -> injective_rfq_rpc.StreamRequestRequest
	6,  // 26: injective_rfq_rpc.InjectiveRfqRPC.Quote:input_type -> injective_rfq_rpc.QuoteRequest
	10, // 27: injective_rfq_rpc.InjectiveRfqRPC.StreamQuote:input_type -> injective_rfq_rpc.StreamQuoteRequest
	13, // 28: injective_rfq_rpc.InjectiveRfqRPC.ListSettlement:input_type -> injective_rfq_rpc.ListSettlementRequest
	19, // 29: injective_rfq_rpc.InjectiveRfqRPC.StreamSettlement:input_type -> injective_rfq_rpc.StreamSettlementRequest
	21, // 30: injective_rfq_rpc.InjectiveRfqRPC.TakerStream:input_type -> injective_rfq_rpc.TakerStreamStreamingRequest
	26, // 31: injective_rfq_rpc.InjectiveRfqRPC.MakerStream:input_type -> injective_rfq_rpc.MakerStreamStreamingRequest
	2,  // 32: injective_rfq_rpc.InjectiveRfqRPC.Request:output_type -> injective_rfq_rpc.RequestResponse
	4,  // 33: injective_rfq_rpc.InjectiveRfqRPC.StreamRequest:output_type -> injective_rfq_rpc.StreamRequestResponse
	9,  // 34: injective_rfq_rpc.InjectiveRfqRPC.Quote:output_type -> injective_rfq_rpc.QuoteResponse
	11, // 35: injective_rfq_rpc.InjectiveRfqRPC.StreamQuote:output_type -> injective_rfq_rpc.StreamQuoteResponse
	14, // 36: injective_rfq_rpc.InjectiveRfqRPC.ListSettlement:output_type -> injective_rfq_rpc.ListSettlementResponse
	20, // 37: injective_rfq_rpc.InjectiveRfqRPC.StreamSettlement:output_type -> injective_rfq_rpc.StreamSettlementResponse
	23, // 38: injective_rfq_rpc.InjectiveRfqRPC.TakerStream:output_type -> injective_rfq_rpc.TakerStreamResponse
	27, // 39: injective_rfq_rpc.InjectiveRfqRPC.MakerStream:output_type -> injective_rfq_rpc.MakerStreamResponse
	32, // [32:40] is the sub-list for method output_type
	24, // [24:32] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_injective_rfq_rpc_proto_init() }
func file_injective_rfq_rpc_proto_init() {
	if File_injective_rfq_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_injective_rfq_rpc_proto_rawDesc), len(file_injective_rfq_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_injective_rfq_rpc_proto_goTypes,
		DependencyIndexes: file_injective_rfq_rpc_proto_depIdxs,
		MessageInfos:      file_injective_rfq_rpc_proto_msgTypes,
	}.Build()
	File_injective_rfq_rpc_proto = out.File
	file_injective_rfq_rpc_proto_goTypes = nil
	file_injective_rfq_rpc_proto_depIdxs = nil
}
