# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import injective_rfq_rpc_pb2 as injective__rfq__rpc__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in injective_rfq_rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InjectiveRfqRPCStub(object):
    """InjectiveRfqRPC defines gRPC API of the RFQ (Request for Quote) API.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Request = channel.unary_unary(
                '/injective_rfq_rpc.InjectiveRfqRPC/Request',
                request_serializer=injective__rfq__rpc__pb2.RequestRequest.SerializeToString,
                response_deserializer=injective__rfq__rpc__pb2.RequestResponse.FromString,
                _registered_method=True)
        self.StreamRequest = channel.unary_stream(
                '/injective_rfq_rpc.InjectiveRfqRPC/StreamRequest',
                request_serializer=injective__rfq__rpc__pb2.StreamRequestRequest.SerializeToString,
                response_deserializer=injective__rfq__rpc__pb2.StreamRequestResponse.FromString,
                _registered_method=True)
        self.Quote = channel.unary_unary(
                '/injective_rfq_rpc.InjectiveRfqRPC/Quote',
                request_serializer=injective__rfq__rpc__pb2.QuoteRequest.SerializeToString,
                response_deserializer=injective__rfq__rpc__pb2.QuoteResponse.FromString,
                _registered_method=True)
        self.StreamQuote = channel.unary_stream(
                '/injective_rfq_rpc.InjectiveRfqRPC/StreamQuote',
                request_serializer=injective__rfq__rpc__pb2.StreamQuoteRequest.SerializeToString,
                response_deserializer=injective__rfq__rpc__pb2.StreamQuoteResponse.FromString,
                _registered_method=True)
        self.ListSettlement = channel.unary_unary(
                '/injective_rfq_rpc.InjectiveRfqRPC/ListSettlement',
                request_serializer=injective__rfq__rpc__pb2.ListSettlementRequest.SerializeToString,
                response_deserializer=injective__rfq__rpc__pb2.ListSettlementResponse.FromString,
                _registered_method=True)
        self.StreamSettlement = channel.unary_stream(
                '/injective_rfq_rpc.InjectiveRfqRPC/StreamSettlement',
                request_serializer=injective__rfq__rpc__pb2.StreamSettlementRequest.SerializeToString,
                response_deserializer=injective__rfq__rpc__pb2.StreamSettlementResponse.FromString,
                _registered_method=True)
        self.TakerStream = channel.stream_stream(
                '/injective_rfq_rpc.InjectiveRfqRPC/TakerStream',
                request_serializer=injective__rfq__rpc__pb2.TakerStreamStreamingRequest.SerializeToString,
                response_deserializer=injective__rfq__rpc__pb2.TakerStreamResponse.FromString,
                _registered_method=True)
        self.MakerStream = channel.stream_stream(
                '/injective_rfq_rpc.InjectiveRfqRPC/MakerStream',
                request_serializer=injective__rfq__rpc__pb2.MakerStreamStreamingRequest.SerializeToString,
                response_deserializer=injective__rfq__rpc__pb2.MakerStreamResponse.FromString,
                _registered_method=True)


class InjectiveRfqRPCServicer(object):
    """InjectiveRfqRPC defines gRPC API of the RFQ (Request for Quote) API.
    """

    def Request(self, request, context):
        """Create RFQ request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRequest(self, request, context):
        """Stream RFQ requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Quote(self, request, context):
        """Create RFQ quote
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamQuote(self, request, context):
        """Stream RFQ quotes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSettlement(self, request, context):
        """List RFQ settlements
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSettlement(self, request, context):
        """Stream RFQ settlements
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TakerStream(self, request_iterator, context):
        """Bidirectional stream for takers: send requests, receive quotes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakerStream(self, request_iterator, context):
        """Bidirectional stream for makers: receive requests, send quotes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InjectiveRfqRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Request': grpc.unary_unary_rpc_method_handler(
                    servicer.Request,
                    request_deserializer=injective__rfq__rpc__pb2.RequestRequest.FromString,
                    response_serializer=injective__rfq__rpc__pb2.RequestResponse.SerializeToString,
            ),
            'StreamRequest': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRequest,
                    request_deserializer=injective__rfq__rpc__pb2.StreamRequestRequest.FromString,
                    response_serializer=injective__rfq__rpc__pb2.StreamRequestResponse.SerializeToString,
            ),
            'Quote': grpc.unary_unary_rpc_method_handler(
                    servicer.Quote,
                    request_deserializer=injective__rfq__rpc__pb2.QuoteRequest.FromString,
                    response_serializer=injective__rfq__rpc__pb2.QuoteResponse.SerializeToString,
            ),
            'StreamQuote': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamQuote,
                    request_deserializer=injective__rfq__rpc__pb2.StreamQuoteRequest.FromString,
                    response_serializer=injective__rfq__rpc__pb2.StreamQuoteResponse.SerializeToString,
            ),
            'ListSettlement': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSettlement,
                    request_deserializer=injective__rfq__rpc__pb2.ListSettlementRequest.FromString,
                    response_serializer=injective__rfq__rpc__pb2.ListSettlementResponse.SerializeToString,
            ),
            'StreamSettlement': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSettlement,
                    request_deserializer=injective__rfq__rpc__pb2.StreamSettlementRequest.FromString,
                    response_serializer=injective__rfq__rpc__pb2.StreamSettlementResponse.SerializeToString,
            ),
            'TakerStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TakerStream,
                    request_deserializer=injective__rfq__rpc__pb2.TakerStreamStreamingRequest.FromString,
                    response_serializer=injective__rfq__rpc__pb2.TakerStreamResponse.SerializeToString,
            ),
            'MakerStream': grpc.stream_stream_rpc_method_handler(
                    servicer.MakerStream,
                    request_deserializer=injective__rfq__rpc__pb2.MakerStreamStreamingRequest.FromString,
                    response_serializer=injective__rfq__rpc__pb2.MakerStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'injective_rfq_rpc.InjectiveRfqRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('injective_rfq_rpc.InjectiveRfqRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InjectiveRfqRPC(object):
    """InjectiveRfqRPC defines gRPC API of the RFQ (Request for Quote) API.
    """

    @staticmethod
    def Request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/injective_rfq_rpc.InjectiveRfqRPC/Request',
            injective__rfq__rpc__pb2.RequestRequest.SerializeToString,
            injective__rfq__rpc__pb2.RequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/injective_rfq_rpc.InjectiveRfqRPC/StreamRequest',
            injective__rfq__rpc__pb2.StreamRequestRequest.SerializeToString,
            injective__rfq__rpc__pb2.StreamRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Quote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/injective_rfq_rpc.InjectiveRfqRPC/Quote',
            injective__rfq__rpc__pb2.QuoteRequest.SerializeToString,
            injective__rfq__rpc__pb2.QuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/injective_rfq_rpc.InjectiveRfqRPC/StreamQuote',
            injective__rfq__rpc__pb2.StreamQuoteRequest.SerializeToString,
            injective__rfq__rpc__pb2.StreamQuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSettlement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/injective_rfq_rpc.InjectiveRfqRPC/ListSettlement',
            injective__rfq__rpc__pb2.ListSettlementRequest.SerializeToString,
            injective__rfq__rpc__pb2.ListSettlementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSettlement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/injective_rfq_rpc.InjectiveRfqRPC/StreamSettlement',
            injective__rfq__rpc__pb2.StreamSettlementRequest.SerializeToString,
            injective__rfq__rpc__pb2.StreamSettlementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TakerStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/injective_rfq_rpc.InjectiveRfqRPC/TakerStream',
            injective__rfq__rpc__pb2.TakerStreamStreamingRequest.SerializeToString,
            injective__rfq__rpc__pb2.TakerStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakerStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/injective_rfq_rpc.InjectiveRfqRPC/MakerStream',
            injective__rfq__rpc__pb2.MakerStreamStreamingRequest.SerializeToString,
            injective__rfq__rpc__pb2.MakerStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
